<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { apiGet, apiPost, apiPut, type ApiError } from './api/client'

type LoginResponse = { access_token: string; refresh_token: string; user: { email: string } }
type SessionState = { accessToken: string; refreshToken: string; userEmail: string }
type ModuleKey = 'overview'|'tenants'|'provisioning'|'domains'|'builds'|'logs'|'branding'|'integrations'|'audit'|'settings'
type Tenant = { id:string;name:string;slug:string;status:string;created_at?:string|null;primary_hostname?:string|null;branding_name?:string|null }
type Domain = { id:string;tenant_id:string;tenant_name?:string;hostname:string;is_primary:boolean;is_temporary:boolean;status:string;validation?:Record<string,unknown> }
type BuildJob = { id:string;tenant?:string;target:string;status:string;created_at?:string|null;source_ref?:string|null;workflow_run_id?:string|null;error?:string|null;artifacts?:Array<{id:string;name:string;download_url?:string|null}> }
type BuildProfile = { id:string;tenant:string;name:string;target:string;api_url:string;bundle_identifier?:string|null;package_name?:string|null;config?:Record<string,unknown> }
type ProvisioningJob = { id:string;tenant_id:string;tenant_name:string;slug:string;status:string;correlation_id:string;created_at?:string|null;steps:Array<{id:string;name:string;status:string;error?:string|null}> }
type Dashboard = { totals:{tenants:number;active_tenants:number;provisioning_jobs:number;domains_pending:number;builds:number;build_artifacts:number;platform_users:number};health:Record<string,string> }
type LogEntry = { id:string;tenant_id?:string|null;tenant_name?:string|null;tenant_slug?:string|null;source:string;service:string;level:string;event:string;message:string;integration?:string|null;error_code?:string|null;details?:Record<string,unknown>;created_at?:string|null }
type LogSummary = { last_24h:{total:number;errors:number;docker:number;integrations:number;tenant_scoped:number};tenant_boundaries:Array<{tenant_id:string;tenant_name:string;slug:string;database_name:string;database_user:string;storage_bucket:string;storage_prefix:string;artifact_prefix:string;isolation_status:string}> }
type AuditEntry = { id:string;user_id?:string|null;email?:string|null;action:string;result:string;ip_address?:string|null;correlation_id?:string|null;metadata:Record<string,unknown>;created_at:string }
type FeatureFlag = { key:string;enabled:boolean;rules:Record<string,unknown> }
type CreatedTenant = { tenant_id:string;tenant_code:string;job_id:string;admin_email:string;initial_admin_password:string;hostname:string;status:string }
type PwaInstaller = { canInstall:boolean;isInstalled:boolean;install:()=>Promise<unknown> }

const storageKey = 'scheduler-pro-admin-session'
const modules = [
  {key:'overview',label:'Visão geral',icon:'▦',description:'Indicadores globais da plataforma'},
  {key:'tenants',label:'Clientes SaaS',icon:'▤',description:'Tenants, credenciais iniciais e recursos isolados'},
  {key:'provisioning',label:'Provisionamento',icon:'⚙',description:'Banco, migrations, storage, DNS, admin e seed'},
  {key:'domains',label:'Domínios',icon:'🌐',description:'DNS temporário, domínio próprio, SSL e cache'},
  {key:'builds',label:'Builds e artefatos',icon:'⬢',description:'PWA, desktop, Android e iOS'},
  {key:'logs',label:'Logs e observabilidade',icon:'◫',description:'Docker, API, tenants e integrações'},
  {key:'branding',label:'Marca e aplicativos',icon:'◇',description:'Perfis de distribuição por cliente'},
  {key:'integrations',label:'Integrações',icon:'⌁',description:'Cloudflare, Evolution, storage e filas'},
  {key:'audit',label:'Auditoria',icon:'☰',description:'Sessões, segurança e ações sensíveis'},
  {key:'settings',label:'Configurações',icon:'⚙',description:'Feature flags e parâmetros globais'},
] as const

const email=ref(''); const password=ref(''); const session=ref<SessionState|null>(null); const errorMessage=ref(''); const toastMessage=ref(''); const loading=ref(false); const activeModule=ref<ModuleKey>('overview'); const sidebarOpen=ref(false); const search=ref(''); const installState=ref({canInstall:false,isInstalled:false})
const dashboard=ref<Dashboard|null>(null); const tenants=ref<Tenant[]>([]); const domains=ref<Domain[]>([]); const builds=ref<BuildJob[]>([]); const profiles=ref<BuildProfile[]>([]); const provisioning=ref<ProvisioningJob[]>([]); const logs=ref<LogEntry[]>([]); const logSummary=ref<LogSummary|null>(null); const integrations=ref<Record<string,unknown>>({}); const audit=ref<AuditEntry[]>([]); const flags=ref<FeatureFlag[]>([]); const createdTenant=ref<CreatedTenant|null>(null)
const tenantForm=ref({name:'',slug:'',admin_email:'',admin_password:''}); const domainForm=ref({tenant_id:'',hostname:'',make_primary:true}); const buildForm=ref({tenant:'',target:'desktop',source_ref:'main'}); const flagForm=ref({key:'',enabled:true,rules:'{}'})

const isAuthenticated=computed(()=>Boolean(session.value?.accessToken))
const selectedModule=computed(()=>modules.find(m=>m.key===activeModule.value)??modules[0])
const query=computed(()=>search.value.trim().toLowerCase())
const filteredTenants=computed(()=>tenants.value.filter(t=>!query.value||`${t.name} ${t.slug} ${t.primary_hostname||''}`.toLowerCase().includes(query.value)))
const filteredDomains=computed(()=>domains.value.filter(d=>!query.value||`${d.hostname} ${d.tenant_name||''} ${d.status}`.toLowerCase().includes(query.value)))
const filteredBuilds=computed(()=>builds.value.filter(b=>!query.value||`${b.target} ${b.status} ${b.source_ref||''}`.toLowerCase().includes(query.value)))

function token():string{return session.value?.accessToken||''}
function formatDate(value?:string|null):string{return value?new Date(value).toLocaleString('pt-BR'):'—'}
function statusClass(value?:string|null):string{return String(value||'').toLowerCase().replace(/[^a-z0-9]+/g,'-')}
function showToast(message:string):void{toastMessage.value=message;window.setTimeout(()=>{if(toastMessage.value===message)toastMessage.value=''},3500)}
function describeError(error:unknown,fallback:string):string{const value=error as Partial<ApiError>;return value?.message||fallback}
function restoreSession():void{const raw=localStorage.getItem(storageKey);if(!raw)return;try{session.value=JSON.parse(raw) as SessionState}catch{localStorage.removeItem(storageKey)}}
function clearSession():void{session.value=null;localStorage.removeItem(storageKey)}

async function login():Promise<void>{loading.value=true;errorMessage.value='';try{const payload=await apiPost<LoginResponse>('/auth/platform/login',{email:email.value,password:password.value});session.value={accessToken:payload.access_token,refreshToken:payload.refresh_token,userEmail:payload.user?.email||email.value};localStorage.setItem(storageKey,JSON.stringify(session.value));password.value='';await refreshAll()}catch(error){errorMessage.value=describeError(error,'Falha no login.')}finally{loading.value=false}}
async function refreshAll():Promise<void>{if(!token())return;loading.value=true;errorMessage.value='';try{const[d,t,dm,b,pv,pr]=await Promise.all([apiGet<Dashboard>('/platform/dashboard',token()),apiGet<Tenant[]>('/platform/tenants',token()),apiGet<Domain[]>('/platform/domains',token()),apiGet<{jobs:BuildJob[]}>('/platform/builds/jobs?limit=100',token()),apiGet<{profiles:BuildProfile[]}>('/platform/builds/profiles',token()),apiGet<ProvisioningJob[]>('/platform/provisioning',token())]);dashboard.value=d;tenants.value=t;domains.value=dm;builds.value=b.jobs||[];profiles.value=pv.profiles||[];provisioning.value=pr;if(activeModule.value==='logs')await loadLogs();if(activeModule.value==='integrations')integrations.value=await apiGet('/platform/integrations/status',token());if(activeModule.value==='audit')audit.value=await apiGet('/platform/audit?limit=300',token());if(activeModule.value==='settings')flags.value=await apiGet('/platform/feature-flags',token())}catch(error){const apiError=error as ApiError;if(apiError.status===401||apiError.status===403)clearSession();errorMessage.value=describeError(error,'Falha ao atualizar Control Plane.')}finally{loading.value=false}}
async function loadLogs():Promise<void>{const[rows,summary]=await Promise.all([apiGet<LogEntry[]>('/platform/observability/logs?limit=300',token()),apiGet<LogSummary>('/platform/observability/logs/summary',token())]);logs.value=rows;logSummary.value=summary}
async function selectModule(key:ModuleKey):Promise<void>{activeModule.value=key;sidebarOpen.value=false;await refreshAll()}
async function createTenant():Promise<void>{try{createdTenant.value=await apiPost('/platform/tenants',{name:tenantForm.value.name,slug:tenantForm.value.slug||null,admin_email:tenantForm.value.admin_email,admin_password:tenantForm.value.admin_password||null},token());tenantForm.value={name:'',slug:'',admin_email:'',admin_password:''};showToast('Tenant criado e provisionamento iniciado.');await refreshAll();activeModule.value='provisioning'}catch(error){errorMessage.value=describeError(error,'Falha ao criar tenant.')}}
async function retryProvision(jobId:string):Promise<void>{try{await apiPost(`/platform/provisioning/${jobId}/retry`,{},token());showToast('Retry enfileirado.');await refreshAll()}catch(error){errorMessage.value=describeError(error,'Falha no retry.')}}
async function temporaryDomain(id:string):Promise<void>{try{await apiPost(`/platform/tenants/${id}/domains/temporary`,{},token());showToast('Domínio temporário verificado.');await refreshAll()}catch(error){errorMessage.value=describeError(error,'Falha no DNS.')}}
async function customDomain():Promise<void>{try{await apiPost(`/platform/tenants/${domainForm.value.tenant_id}/domains/custom`,{hostname:domainForm.value.hostname,make_primary:domainForm.value.make_primary},token());domainForm.value.hostname='';showToast('Domínio próprio enviado.');await refreshAll()}catch(error){errorMessage.value=describeError(error,'Falha ao conectar domínio.')}}
async function checkDomain(id:string):Promise<void>{try{await apiPost(`/platform/domains/${id}/check`,{},token());showToast('Verificação concluída.');await refreshAll()}catch(error){errorMessage.value=describeError(error,'Falha na verificação.')}}
async function purgeDomain(id:string):Promise<void>{try{await apiPost(`/platform/domains/${id}/purge-cache`,{},token());showToast('Purge executado.');await loadLogs()}catch(error){errorMessage.value=describeError(error,'Falha no purge.')}}
async function createBuild():Promise<void>{try{await apiPost('/platform/builds/requests',{...buildForm.value,requested_by:session.value?.userEmail,payload:{origin:'admin-pwa'}},token());showToast('Build persistido e dispatch solicitado.');await refreshAll()}catch(error){errorMessage.value=describeError(error,'Falha no build.')}}
async function refreshBuild(id:string):Promise<void>{try{await apiPost(`/platform/builds/jobs/${id}/refresh`,{},token());await refreshAll()}catch(error){errorMessage.value=describeError(error,'Falha ao sincronizar build.')}}
async function saveFlag():Promise<void>{try{let rules:Record<string,unknown>;try{rules=JSON.parse(flagForm.value.rules) as Record<string,unknown>}catch{throw new Error('Rules deve ser JSON válido.')}await apiPut(`/platform/feature-flags/${encodeURIComponent(flagForm.value.key)}`,{enabled:flagForm.value.enabled,rules},token());flagForm.value={key:'',enabled:true,rules:'{}'};flags.value=await apiGet('/platform/feature-flags',token());showToast('Feature flag salva.')}catch(error){errorMessage.value=error instanceof Error?error.message:'Falha na flag.'}}
function updateInstallState():void{const installer=(window as unknown as{schedulerProAdminPwa?:PwaInstaller}).schedulerProAdminPwa;installState.value={canInstall:Boolean(installer?.canInstall),isInstalled:Boolean(installer?.isInstalled)}}
async function installPwa():Promise<void>{const installer=(window as unknown as{schedulerProAdminPwa?:PwaInstaller}).schedulerProAdminPwa;if(installer?.isInstalled){showToast('Control Plane já está instalado.');return}if(installer?.canInstall){await installer.install();updateInstallState()}}
function logout():void{clearSession();dashboard.value=null}

onMounted(()=>{restoreSession();updateInstallState();if(token())void refreshAll();window.addEventListener('scheduler-pro-admin-install-state',updateInstallState)})
onUnmounted(()=>window.removeEventListener('scheduler-pro-admin-install-state',updateInstallState))
</script>

<template>
<main class="admin-root">
<section v-if="!isAuthenticated" class="auth-page"><aside class="auth-visual"><div class="auth-brand"><div class="brand-mark">SP</div><div><strong>Scheduler Pro</strong><span>Control Plane</span></div></div><h1>Controle tenants, infraestrutura, integrações e distribuições.</h1><p>Administração responsiva no padrão operacional do Hub Fiscal.</p></aside><form class="auth-card" @submit.prevent="login"><h2>Acessar Control Plane</h2><label>E-mail<input v-model="email" type="email" autocomplete="username" required/></label><label>Senha<input v-model="password" type="password" autocomplete="current-password" required/></label><p v-if="errorMessage" class="form-error">{{errorMessage}}</p><button class="btn primary full" :disabled="loading">{{loading?'Validando...':'Entrar'}}</button></form></section>
<div v-else class="admin-shell" :class="{sidebarOpen}"><aside class="sidebar"><div class="brand"><div class="brand-mark">SP</div><div><strong>Scheduler Pro</strong><small>Control Plane</small></div></div><nav><button v-for="item in modules" :key="item.key" :class="{active:activeModule===item.key}" @click="selectModule(item.key as ModuleKey)"><span>{{item.icon}}</span><div><strong>{{item.label}}</strong><small>{{item.description}}</small></div></button></nav><div class="sidebar-footer"><button @click="logout"><span>⇥</span><div><strong>Sair</strong><small>{{session?.userEmail}}</small></div></button></div></aside>
<section class="workspace"><header class="topbar"><button class="icon-button" @click="sidebarOpen=!sidebarOpen">☰</button><div><small>Scheduler Pro</small><strong>{{selectedModule.label}}</strong></div><div class="search"><input v-model="search" placeholder="Buscar na plataforma"/></div><div class="topbar-spacer"></div><button v-if="installState.canInstall&&!installState.isInstalled" class="btn" @click="installPwa">Instalar</button><button class="btn primary" @click="refreshAll">Atualizar</button></header>
<main class="main-content"><section class="page-header"><div><p class="eyebrow">Control Plane</p><h1>{{selectedModule.label}}</h1><p>{{selectedModule.description}}</p></div></section><p v-if="toastMessage" class="success-banner">{{toastMessage}}</p><p v-if="errorMessage" class="error-banner">{{errorMessage}}</p>
<section class="metric-grid"><article class="metric-card blue"><div><span>Clientes</span><strong>{{dashboard?.totals.tenants??0}}</strong><small>{{dashboard?.totals.active_tenants??0}} ativos</small></div></article><article class="metric-card violet"><div><span>Provisionamentos</span><strong>{{dashboard?.totals.provisioning_jobs??0}}</strong><small>jobs</small></div></article><article class="metric-card green"><div><span>Domínios pendentes</span><strong>{{dashboard?.totals.domains_pending??0}}</strong><small>DNS / SSL</small></div></article><article class="metric-card orange"><div><span>Artefatos</span><strong>{{dashboard?.totals.build_artifacts??0}}</strong><small>{{dashboard?.totals.builds??0}} builds</small></div></article></section>

<section v-if="activeModule==='overview'" class="dashboard-grid"><article class="panel span-2"><h3>Tenants recentes</h3><div class="rows"><article v-for="tenant in tenants.slice(0,8)" :key="tenant.id"><div><strong>{{tenant.name}}</strong><small>{{tenant.slug}} • {{tenant.primary_hostname||'domínio pendente'}}</small></div><span :class="['status',statusClass(tenant.status)]">{{tenant.status}}</span></article></div></article><article class="panel"><h3>Saúde</h3><div class="health-list"><div v-for="(value,key) in dashboard?.health||{}" :key="key"><span>{{key}}</span><strong>{{value}}</strong></div></div></article></section>

<section v-else-if="activeModule==='tenants'" class="two-column"><article class="panel"><h3>Novo cliente SaaS</h3><form class="stack-form" @submit.prevent="createTenant"><input v-model="tenantForm.name" placeholder="Nome da empresa" required/><input v-model="tenantForm.slug" placeholder="Código opcional"/><input v-model="tenantForm.admin_email" type="email" placeholder="E-mail administrador" required/><input v-model="tenantForm.admin_password" type="password" minlength="12" placeholder="Senha opcional (gera automática se vazio)"/><button class="btn primary">Criar e provisionar</button></form><article v-if="createdTenant" class="credential-card"><strong>Credencial inicial</strong><span>{{createdTenant.admin_email}}</span><code>{{createdTenant.initial_admin_password}}</code><small>Copie agora e entregue ao cliente.</small></article></article><article class="panel span-2"><h3>Clientes</h3><div class="data-table"><div class="table-head"><span>Cliente</span><span>Domínio</span><span>Status</span><span>Ação</span></div><div v-for="tenant in filteredTenants" :key="tenant.id" class="table-row"><span><strong>{{tenant.name}}</strong><small>{{tenant.slug}}</small></span><span>{{tenant.primary_hostname||'—'}}</span><span :class="['status',statusClass(tenant.status)]">{{tenant.status}}</span><span><button class="btn small" @click="temporaryDomain(tenant.id)">DNS temporário</button></span></div></div></article></section>

<section v-else-if="activeModule==='provisioning'" class="view-stack"><article v-for="job in provisioning" :key="job.id" class="panel provisioning-card"><div class="panel-title"><div><h3>{{job.tenant_name}}</h3><p>{{job.slug}} • {{formatDate(job.created_at)}} • {{job.correlation_id}}</p></div><div><span :class="['status',statusClass(job.status)]">{{job.status}}</span><button v-if="job.status==='FAILED'" class="btn small" @click="retryProvision(job.id)">Tentar novamente</button></div></div><div class="step-grid"><article v-for="step in job.steps" :key="step.id" :class="['step',statusClass(step.status)]"><strong>{{step.name}}</strong><span>{{step.status}}</span><small v-if="step.error">{{step.error}}</small></article></div></article></section>

<section v-else-if="activeModule==='domains'" class="two-column"><article class="panel"><h3>Domínio próprio</h3><form class="stack-form" @submit.prevent="customDomain"><select v-model="domainForm.tenant_id" required><option value="">Selecione o tenant</option><option v-for="tenant in tenants" :key="tenant.id" :value="tenant.id">{{tenant.name}}</option></select><input v-model="domainForm.hostname" placeholder="agenda.cliente.com.br" required/><label class="check-line"><input v-model="domainForm.make_primary" type="checkbox"/> Tornar primário</label><button class="btn primary">Conectar</button></form></article><article class="panel span-2"><h3>Domínios registrados</h3><div class="data-table"><div class="table-head"><span>Hostname</span><span>Tenant</span><span>Status</span><span>Ações</span></div><div v-for="domain in filteredDomains" :key="domain.id" class="table-row"><span><strong>{{domain.hostname}}</strong><small>{{domain.is_temporary?'temporário':'personalizado'}} {{domain.is_primary?'• primário':''}}</small></span><span>{{domain.tenant_name}}</span><span :class="['status',statusClass(domain.status)]">{{domain.status}}</span><span class="actions"><button class="btn small" @click="checkDomain(domain.id)">Verificar</button><button class="btn small" @click="purgeDomain(domain.id)">Purge</button></span></div></div></article></section>

<section v-else-if="activeModule==='builds'" class="two-column"><article class="panel"><h3>Solicitar distribuição</h3><form class="stack-form" @submit.prevent="createBuild"><select v-model="buildForm.tenant" required><option value="">Tenant</option><option v-for="tenant in tenants" :key="tenant.id" :value="tenant.id">{{tenant.name}}</option></select><select v-model="buildForm.target"><option value="web">Web</option><option value="pwa">PWA</option><option value="desktop">Desktop cliente</option><option value="android">Android cliente</option><option value="ios">iOS cliente</option><option value="admin-desktop">Desktop admin</option><option value="admin-android">Android admin</option><option value="admin-ios">iOS admin</option></select><input v-model="buildForm.source_ref" placeholder="main"/><button class="btn primary">Disparar build</button></form></article><article class="panel span-2"><h3>Jobs</h3><div class="rows"><article v-for="build in filteredBuilds" :key="build.id"><div><strong>{{build.target}} • {{build.status}}</strong><small>{{formatDate(build.created_at)}} • run {{build.workflow_run_id||'aguardando'}}</small><p v-if="build.error" class="error-text">{{build.error}}</p></div><button class="btn small" @click="refreshBuild(build.id)">Sincronizar</button></article></div></article></section>

<section v-else-if="activeModule==='logs'" class="view-stack"><article class="metric-grid compact"><div class="metric-card"><span>24h</span><strong>{{logSummary?.last_24h.total??0}}</strong></div><div class="metric-card"><span>Erros</span><strong>{{logSummary?.last_24h.errors??0}}</strong></div><div class="metric-card"><span>Integrações</span><strong>{{logSummary?.last_24h.integrations??0}}</strong></div></article><article class="panel"><h3>Logs registrados</h3><div class="log-list"><details v-for="log in logs" :key="log.id"><summary><strong>{{log.level}} • {{log.source}} • {{log.event}}</strong><small>{{formatDate(log.created_at)}} • {{log.tenant_name||log.tenant_slug||'plataforma'}} • {{log.message}}</small></summary><pre>{{JSON.stringify(log.details||{error_code:log.error_code,integration:log.integration},null,2)}}</pre></details></div></article><article class="panel"><h3>Isolamento por tenant</h3><div class="data-table"><div class="table-head"><span>Tenant</span><span>Banco</span><span>Storage</span><span>Artefatos</span></div><div v-for="boundary in logSummary?.tenant_boundaries||[]" :key="boundary.tenant_id" class="table-row"><span>{{boundary.tenant_name}}</span><span>{{boundary.database_name}}</span><span>{{boundary.storage_bucket}}</span><span>{{boundary.artifact_prefix}}</span></div></div></article></section>

<section v-else-if="activeModule==='branding'" class="view-stack"><article class="panel"><h3>Perfis de distribuição</h3><p>Desktop usa WebView remoto do domínio web; mobile continua dedicado e conectado à API.</p><div class="data-table"><div class="table-head"><span>Tenant</span><span>Alvo</span><span>Nome</span><span>Endpoint</span></div><div v-for="profile in profiles" :key="profile.id" class="table-row"><span>{{profile.tenant}}</span><span>{{profile.target}}</span><span>{{profile.name}}</span><span>{{profile.api_url}}</span></div></div></article></section>

<section v-else-if="activeModule==='integrations'" class="integration-cards"><article v-for="(value,key) in integrations" :key="key" class="panel"><h3>{{key}}</h3><pre>{{JSON.stringify(value,null,2)}}</pre></article></section>

<section v-else-if="activeModule==='audit'" class="view-stack"><article class="panel"><h3>Auditoria da plataforma</h3><div class="data-table"><div class="table-head"><span>Data</span><span>Usuário</span><span>Ação</span><span>Resultado</span></div><div v-for="entry in audit" :key="entry.id" class="table-row"><span>{{formatDate(entry.created_at)}}</span><span>{{entry.email||entry.user_id||'sistema'}}</span><span>{{entry.action}}</span><span :class="['status',statusClass(entry.result)]">{{entry.result}}</span></div></div></article></section>

<section v-else class="two-column"><article class="panel"><h3>Feature flag</h3><form class="stack-form" @submit.prevent="saveFlag"><input v-model="flagForm.key" placeholder="chave" required/><label class="check-line"><input v-model="flagForm.enabled" type="checkbox"/> Habilitada</label><textarea v-model="flagForm.rules" rows="8" placeholder="{}"></textarea><button class="btn primary">Salvar</button></form></article><article class="panel span-2"><h3>Flags cadastradas</h3><div class="rows"><article v-for="flag in flags" :key="flag.key"><div><strong>{{flag.key}}</strong><small>{{JSON.stringify(flag.rules)}}</small></div><span :class="['status',flag.enabled?'active':'inactive']">{{flag.enabled?'ON':'OFF'}}</span></article></div></article></section>
</main></section></div></main>
</template>
