import { deepClone, getNode, normalizeDocument } from './model.js';
import { conservativeHtml, escapeHtml, safeUrl, sanitizeStyleValue } from './sanitize.js';

const CUSTOM_RENDERERS = new Map();
export function registerRenderer(type, renderer) { if (typeof renderer !== 'function') throw new Error('Renderer inválido.'); CUSTOM_RENDERERS.set(type, renderer); }
export function unregisterRenderer(type) { CUSTOM_RENDERERS.delete(type); }
const SCHEDULER_SUPPORTED = new Set(['section','container','columns','grid','hero','title','subtitle','text','logo','image','gallery','video','button','whatsapp_button','social','divider','spacer','card','cards','services','professionals','booking','calendar','form','business_hours','address','map','contact','faq','testimonials','cta','notices','policies','footer']);
const UNIT_LESS = new Set(['fontWeight','opacity','zIndex','order','flexGrow','flexShrink','lineHeight']);
const PX_PROPS = new Set(['fontSize','borderRadius','gap','padding','paddingTop','paddingRight','paddingBottom','paddingLeft','margin','marginTop','marginRight','marginBottom','marginLeft','width','maxWidth','minHeight','height','letterSpacing']);
function cssName(key) { return key.replace(/[A-Z]/g, match => `-${match.toLowerCase()}`); }
function cssValue(key, value) { if (value == null || value === '') return ''; if (typeof value === 'number' && PX_PROPS.has(key) && !UNIT_LESS.has(key)) return `${value}px`; return sanitizeStyleValue(value); }
function styleObject(node, device = 'desktop') { const base = { ...(node.style || {}) }; if (device === 'tablet' || device === 'mobile') Object.assign(base, node.responsive?.tablet || {}); if (device === 'mobile') Object.assign(base, node.responsive?.mobile || {}); if (node.type === 'container') Object.assign(base, { display:'flex', flexDirection:node.props.direction || 'column', gap:Number(node.props.gap ?? 20), maxWidth:Number(node.props.max_width ?? 1180), marginLeft:'auto', marginRight:'auto' }); if (node.type === 'grid') Object.assign(base, { display:'grid', gridTemplateColumns:`repeat(${Math.max(1, Number(node.props.columns || 3))}, minmax(0,1fr))`, gap:Number(node.props.gap ?? 20) }); return base; }
function styleText(style) { return Object.entries(style).map(([key, value]) => { const v = cssValue(key, value); return v ? `${cssName(key)}:${v}` : ''; }).filter(Boolean).join(';'); }
function hidden(node, device) { return Boolean(node.responsive?.hidden?.[device]); }
function parseListText(value, mode = 'generic') { return String(value || '').split(/\r?\n/).map(s => s.trim()).filter(Boolean).map(line => { const [left, ...rest] = line.split('|'); const right = rest.join('|').trim(); if (mode === 'faq') return { question:left.trim(), answer:right }; if (mode === 'testimonial') return { name:left.trim(), text:right }; return { title:left.trim(), text:right }; }); }
export function materializeProps(node) { const props = deepClone(node.props || {}); if (node.type === 'gallery' && typeof props.images_text === 'string') props.images = props.images_text.split(/\r?\n/).map(s=>s.trim()).filter(Boolean); if (node.type === 'faq' && typeof props.items_text === 'string') props.items = parseListText(props.items_text, 'faq'); if (node.type === 'testimonials' && typeof props.items_text === 'string') props.items = parseListText(props.items_text, 'testimonial'); delete props.images_text; delete props.items_text; return props; }
export function toSchedulerProContent(input) { const doc = normalizeDocument(input); const blocks = []; const visit = id => { const node = getNode(doc, id); if (!node) return; if (node.type === 'container' || node.type === 'grid') { node.children.forEach(visit); return; } let type = node.type; const props = materializeProps(node); if (type === 'heading') { type = props.level === 'h3' || props.level === 'h4' ? 'subtitle' : 'title'; props.text = props.text || props.title || ''; delete props.level; } if (type === 'html') { type = 'text'; props.text = String(props.html || '').replace(/<[^>]+>/g, ' ').replace(/\s+/g,' ').trim(); delete props.html; } if (!SCHEDULER_SUPPORTED.has(type)) type = 'text'; blocks.push({ id:node.id, type, props, style:deepClone(node.style || {}), responsive:deepClone(node.responsive || {}) }); node.children.forEach(visit); }; doc.builder.root_ids.forEach(visit); if (!blocks.length) blocks.push({ id:'upb-empty', type:'text', props:{title:'',text:''}, style:{}, responsive:{desktop:{},tablet:{},mobile:{},hidden:{desktop:false,tablet:false,mobile:false}} }); return { version:Math.max(2, Number(doc.version || 2)), title:doc.title, global_styles:deepClone(doc.global_styles || {}), seo:deepClone(doc.seo || {}), blocks, builder:deepClone(doc.builder) }; }
function renderChildren(doc, node, device, context) { return node.children.map(id => renderNode(doc, getNode(doc,id), device, context)).join(''); }
function attrStyle(node, device) { return escapeHtml(styleText(styleObject(node, device))); }
function img(src, alt='Imagem') { const url=safeUrl(src,''); return url ? `<img src="${escapeHtml(url)}" alt="${escapeHtml(alt)}" loading="lazy">` : '<div class="upb-empty">Adicione uma imagem.</div>'; }
export function renderNode(doc, node, device='desktop', context={}) {
  if (!node || hidden(node, device)) return '';
  const p = materializeProps(node); const s = attrStyle(node, device); const id=escapeHtml(node.id); const cls=`upb-node upb-${escapeHtml(node.type)}`;
  const wrap = inner => `<section class="${cls}" data-upb-node="${id}" style="${s}">${inner}</section>`;
  const custom=CUSTOM_RENDERERS.get(node.type); if(custom){const output=custom({document:doc,node,props:p,device,context,wrap,escapeHtml,safeUrl,renderChildren:()=>renderChildren(doc,node,device,context)});if(typeof output==='string')return output;}
  switch (node.type) {
    case 'container': case 'grid': return wrap(renderChildren(doc,node,device,context) || '<div class="upb-empty">Arraste elementos para este container.</div>');
    case 'hero': return wrap(`<div class="upb-hero-copy">${p.eyebrow?`<span class="upb-eyebrow">${escapeHtml(p.eyebrow)}</span>`:''}<h1>${escapeHtml(p.title)}</h1><p>${escapeHtml(p.text)}</p>${p.cta?`<a class="upb-btn" href="#agendamento">${escapeHtml(p.cta)}</a>`:''}</div>${p.image?`<figure>${img(p.image,p.title)}</figure>`:''}`);
    case 'heading': { const level=['h1','h2','h3','h4'].includes(p.level)?p.level:'h2'; return wrap(`<${level}>${escapeHtml(p.text)}</${level}>`); }
    case 'title': return wrap(`<h2>${escapeHtml(p.text)}</h2>`); case 'subtitle': return wrap(`<h3>${escapeHtml(p.text)}</h3>`); case 'text': return wrap(`${p.title?`<h2>${escapeHtml(p.title)}</h2>`:''}<p>${escapeHtml(p.text)}</p>`);
    case 'button': return wrap(`<a class="upb-btn" href="${escapeHtml(safeUrl(p.url))}">${escapeHtml(p.label)}</a>`); case 'image': case 'logo': return wrap(img(p.image,p.alt));
    case 'video': return wrap(`<h2>${escapeHtml(p.title)}</h2>${p.url?`<a class="upb-btn upb-btn-secondary" href="${escapeHtml(safeUrl(p.url))}" target="_blank" rel="noopener noreferrer">Abrir vídeo</a>`:''}`);
    case 'divider': return `<div class="${cls}" data-upb-node="${id}"><hr></div>`; case 'spacer': return `<div class="${cls}" data-upb-node="${id}" style="height:${Math.max(0,Number(p.height||32))}px"></div>`;
    case 'gallery': return wrap(`<h2>${escapeHtml(p.title)}</h2><div class="upb-gallery">${(p.images||[]).map((url,i)=>`<figure>${img(url,`${p.title||'Galeria'} ${i+1}`)}</figure>`).join('')}</div>`);
    case 'card': return wrap(`<article class="upb-card"><h3>${escapeHtml(p.title)}</h3><p>${escapeHtml(p.text)}</p></article>`);
    case 'services': return wrap(`<span class="upb-eyebrow">Atendimentos</span><h2>${escapeHtml(p.title)}</h2><p>${escapeHtml(p.subtitle)}</p><div class="upb-dynamic" data-upb-dynamic="services">${context.servicesHtml || 'Os serviços são carregados pelo projeto hospedeiro.'}</div>`);
    case 'professionals': return wrap(`<span class="upb-eyebrow">Equipe</span><h2>${escapeHtml(p.title)}</h2><div class="upb-dynamic" data-upb-dynamic="professionals">${context.professionalsHtml || 'Os profissionais são carregados pelo projeto hospedeiro.'}</div>`);
    case 'booking': case 'calendar': case 'form': return `<section id="agendamento" class="${cls}" data-upb-node="${id}" style="${s}"><span class="upb-eyebrow">Agenda</span><h2>${escapeHtml(p.title||'Agende seu horário')}</h2><p>${escapeHtml(p.subtitle||'')}</p><div class="upb-dynamic" data-upb-dynamic="booking">${context.bookingHtml || 'O componente de agendamento é injetado aqui pelo projeto hospedeiro.'}</div></section>`;
    case 'testimonials': return wrap(`<h2>${escapeHtml(p.title)}</h2><div class="upb-cards">${(p.items||[]).map(item=>`<blockquote class="upb-card"><p>“${escapeHtml(item.text)}”</p><strong>${escapeHtml(item.name||item.title||'')}</strong></blockquote>`).join('') || '<div class="upb-empty">Adicione depoimentos.</div>'}</div>`);
    case 'faq': return wrap(`<h2>${escapeHtml(p.title)}</h2>${(p.items||[]).map(item=>`<details><summary>${escapeHtml(item.question||item.title)}</summary><p>${escapeHtml(item.answer||item.text)}</p></details>`).join('') || '<div class="upb-empty">Adicione perguntas.</div>'}`);
    case 'business_hours': return wrap(`<h2>${escapeHtml(p.title)}</h2><p>Consulte os horários disponíveis.</p>`); case 'address': case 'map': return wrap(`<h2>${escapeHtml(p.title)}</h2><p>${escapeHtml(p.address||'Informe o endereço.')}</p>`);
    case 'contact': return wrap(`<h2>${escapeHtml(p.title)}</h2>${p.phone?`<a href="tel:${escapeHtml(String(p.phone))}">${escapeHtml(p.phone)}</a>`:''}${p.email?`<a href="mailto:${escapeHtml(String(p.email))}">${escapeHtml(p.email)}</a>`:''}`);
    case 'social': return wrap(`<h2>${escapeHtml(p.title)}</h2><div class="upb-social">${['instagram','facebook','tiktok'].filter(k=>p[k]).map(k=>`<a href="${escapeHtml(safeUrl(p[k]))}" target="_blank" rel="noopener noreferrer">${escapeHtml(k)}</a>`).join('')}</div>`);
    case 'whatsapp_button': { const digits=String(p.phone||'').replace(/\D/g,''); return wrap(`<a class="upb-btn" href="${digits?`https://wa.me/${digits}`:'#agendamento'}" target="_blank" rel="noopener noreferrer">${escapeHtml(p.label)}</a>`); }
    case 'cta': return wrap(`<div><h2>${escapeHtml(p.title)}</h2><p>${escapeHtml(p.text)}</p></div><a class="upb-btn" href="#agendamento">${escapeHtml(p.button)}</a>`); case 'footer': return `<footer class="${cls}" data-upb-node="${id}" style="${s}">${escapeHtml(p.text)}</footer>`; case 'html': return wrap(conservativeHtml(p.html));
    default: return wrap(`${p.title?`<h2>${escapeHtml(p.title)}</h2>`:''}${p.text?`<p>${escapeHtml(p.text)}</p>`:''}${renderChildren(doc,node,device,context)}`);
  }
}
export function baseRenderCss(globalStyles={}) { const g={primary:'#3151cf',secondary:'#151c31',accent:'#6d72ef',background:'#fff',text:'#1d273a',heading_font:'Inter',body_font:'Inter',radius:16,...globalStyles}; return `.upb-page{--upb-primary:${sanitizeStyleValue(g.primary)};--upb-secondary:${sanitizeStyleValue(g.secondary)};--upb-accent:${sanitizeStyleValue(g.accent)};--upb-bg:${sanitizeStyleValue(g.background)};--upb-text:${sanitizeStyleValue(g.text)};--upb-radius:${Number(g.radius)||16}px;--upb-heading:${sanitizeStyleValue(g.heading_font)};--upb-body:${sanitizeStyleValue(g.body_font)}}*{box-sizing:border-box}.upb-page{min-height:100%;background:var(--upb-bg);color:var(--upb-text);font-family:var(--upb-body),system-ui,sans-serif;overflow-x:hidden}.upb-node{width:min(calc(100% - 32px),1180px);margin:0 auto;padding:clamp(28px,5vw,72px) 0}.upb-node h1,.upb-node h2,.upb-node h3,.upb-node h4{font-family:var(--upb-heading),system-ui,sans-serif;margin:0 0 .55em;line-height:1.05}.upb-node h1{font-size:clamp(42px,7vw,88px)}.upb-node h2{font-size:clamp(28px,4vw,48px)}.upb-node p{line-height:1.65}.upb-container,.upb-grid{padding:20px}.upb-container>.upb-node,.upb-grid>.upb-node{width:100%;margin:0;padding:0}.upb-hero{width:100%;max-width:none;padding:clamp(54px,8vw,110px) max(20px,calc((100% - 1180px)/2));display:grid;grid-template-columns:minmax(0,1.1fr) minmax(280px,.9fr);align-items:center;gap:48px;background:var(--upb-secondary);color:#fff}.upb-hero figure{margin:0}.upb-hero img,.upb-image img,.upb-gallery img{display:block;width:100%;height:auto;border-radius:var(--upb-radius)}.upb-eyebrow{text-transform:uppercase;letter-spacing:.12em;font-weight:800;font-size:.75rem;color:var(--upb-accent)}.upb-btn{display:inline-flex;align-items:center;justify-content:center;padding:13px 20px;border-radius:calc(var(--upb-radius)*.7);background:var(--upb-primary);color:#fff;text-decoration:none;font-weight:800}.upb-gallery,.upb-cards{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}.upb-card,.upb-dynamic,.upb-empty{padding:20px;border:1px solid color-mix(in srgb,var(--upb-text) 14%,transparent);border-radius:var(--upb-radius);background:color-mix(in srgb,var(--upb-bg) 97%,var(--upb-text))}.upb-footer{text-align:center;padding:28px}@media(max-width:1024px){.upb-hero{grid-template-columns:1fr}.upb-gallery,.upb-cards{grid-template-columns:repeat(2,minmax(0,1fr))}.upb-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}}@media(max-width:680px){.upb-node{width:min(calc(100% - 24px),1180px);padding:36px 0}.upb-hero{padding:54px 20px}.upb-gallery,.upb-cards,.upb-grid{grid-template-columns:1fr!important}}`; }
export function renderDocument(input, { device='desktop', context={} } = {}) { const doc=normalizeDocument(input); let html=doc.builder.root_ids.map(id=>renderNode(doc,getNode(doc,id),device,context)).join(''); const hasBooking=Object.values(doc.builder.nodes).some(node=>['booking','calendar','form'].includes(node.type)); if(context.ensureBooking&&!hasBooking)html+=`<section id="agendamento" class="upb-node upb-booking"><span class="upb-eyebrow">Agenda</span><h2>Agende seu horário</h2><div class="upb-dynamic" data-upb-dynamic="booking">${context.bookingHtml||'O componente de agendamento é injetado aqui pelo projeto hospedeiro.'}</div></section>`; return { html:`<main class="upb-page" data-upb-device="${escapeHtml(device)}">${html}</main>`, css:baseRenderCss(doc.global_styles), document:doc }; }
export function exportStandaloneHtml(input, options={}) { const {html,css,document:doc}=renderDocument(input,{device:'desktop',context:options.context||{}}); const title=escapeHtml(doc.seo?.title||doc.title||'Página'); const description=escapeHtml(doc.seo?.description||''); return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><meta name="description" content="${description}"><style>${css}</style></head><body>${html}</body></html>`; }
