import { addNode, createDocument, createNode, deepClone, duplicateNode, getNode, moveNode, normalizeDocument, parentOf, removeNode } from './model.js';
import { HistoryStack } from './history.js';
import { createProps, widgetDefinition, widgetGroups } from './registry.js';
import { baseRenderCss, exportStandaloneHtml, renderDocument } from './renderer.js';
import { escapeHtml } from './sanitize.js';
import { MemoryAdapter } from './adapters.js';
import { BUILTIN_TEMPLATES } from './templates.js';
import { EDITOR_CSS } from './editor-styles.js';

const DEVICE_LABELS={desktop:'Desktop',tablet:'Tablet',mobile:'Mobile'};
const DEVICE_ICONS={desktop:'▰',tablet:'▯',mobile:'▯'};
function esc(value){return escapeHtml(value);}
function download(name, content, type='application/json'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function toNumber(value){const n=Number(value);return Number.isFinite(n)?n:0;}

const HTMLElementBase = globalThis.HTMLElement || class {};
export class ArgwsVisualBuilder extends HTMLElementBase {
  constructor(){super();this.attachShadow({mode:'open'});this._adapter=new MemoryAdapter();this._document=createDocument();this._history=new HistoryStack(100);this._history.reset(this._document);this._selected=null;this._device='desktop';this._mobileDrawer=null;this._leftTab='elements';this._rightTab='content';this._dirty=false;this._loading=false;this._saving=false;this._publishing=false;this._search='';this._remoteTemplates=[];this._autosaveTimer=null;this._connected=false;this._keyboard=this._onKeyboard.bind(this);}
  set adapter(value){this._adapter=value||new MemoryAdapter();} get adapter(){return this._adapter;}
  set document(value){this._document=normalizeDocument(value);this._history.reset(this._document);this._selected=this._document.builder.root_ids[0]||null;this._dirty=false;if(this._connected)this._renderAll();} get document(){return deepClone(this._document);}
  connectedCallback(){if(this._connected)return;this._connected=true;this._renderShell();this._bind();this._renderAll();globalThis.addEventListener?.('keydown',this._keyboard);if(this.hasAttribute('autoload'))void this.load();}
  disconnectedCallback(){globalThis.removeEventListener?.('keydown',this._keyboard);if(this._autosaveTimer)clearTimeout(this._autosaveTimer);}
  _renderShell(){this.shadowRoot.innerHTML=`<style>${EDITOR_CSS}</style><div class="shell"><header class="topbar"><div class="brand"><span class="brand-mark">A</span><span>ARGWS Visual Builder</span></div><button class="btn icon" data-action="undo" title="Desfazer (Ctrl+Z)">↶</button><button class="btn icon" data-action="redo" title="Refazer (Ctrl+Y)">↷</button><div class="device-actions">${Object.entries(DEVICE_LABELS).map(([key,label])=>`<button class="btn" data-device="${key}" title="${label}">${DEVICE_ICONS[key]} ${label}</button>`).join('')}</div><button class="btn icon mobile-only" data-action="mobile-left" title="Elementos">＋</button><button class="btn icon mobile-only" data-action="mobile-right" title="Propriedades">⚙</button><div class="top-spacer"></div><span id="save-status" style="font-size:11px;color:var(--muted)"></span><button class="btn" data-action="import">Importar</button><button class="btn" data-action="export-json">JSON</button><button class="btn" data-action="export-html">HTML</button><button class="btn" data-action="preview">Preview</button><button class="btn" data-action="save">Salvar</button><button class="btn primary" data-action="publish">Publicar</button><button class="btn icon danger" data-action="close" title="Fechar">×</button><input id="import-file" type="file" accept="application/json,.json" hidden></header><div class="work"><aside class="panel left"><div class="tabs"><button class="tab" data-left="elements">Elementos</button><button class="tab" data-left="layers">Camadas</button><button class="tab" data-left="templates">Modelos</button></div><div id="left-panel" class="panel-scroll"></div></aside><main class="canvas-zone"><div class="canvas-toolbar"><span id="canvas-label"></span></div><div class="canvas-scroller"><div id="canvas-frame" class="canvas-frame"><div id="page-preview" class="page-preview"></div><div class="drop-root" data-drop-root></div></div></div></main><aside class="panel right"><div id="inspector-head" class="inspector-head"></div><div class="tabs"><button class="tab" data-right="content">Conteúdo</button><button class="tab" data-right="style">Estilo</button><button class="tab" data-right="advanced">Avançado</button></div><div id="right-panel" class="panel-scroll"></div></aside></div><div class="mobile-backdrop" data-action="mobile-close"></div><div id="notice-host"></div></div>`;}
  _bind(){const root=this.shadowRoot;root.addEventListener('click',event=>this._onClick(event));root.addEventListener('input',event=>this._onInput(event));root.addEventListener('change',event=>this._onChange(event));root.addEventListener('dragstart',event=>this._onDragStart(event));root.addEventListener('dragover',event=>this._onDragOver(event));root.addEventListener('drop',event=>this._onDrop(event));root.getElementById('import-file').addEventListener('change',event=>void this._importFile(event));}
  async load(){this._loading=true;this._status('Carregando…');try{const doc=await this._adapter.load();this.document=doc;this._remoteTemplates=await this._adapter.listTemplates?.().catch?.(()=>[])||[];this._notice('Página carregada.');}catch(error){this._notice(error?.message||'Falha ao carregar a página.','error');throw error;}finally{this._loading=false;this._status('');this._renderAll();}}
  async save({autosave=false}={}){if(this._saving||!this._dirty)return null;this._saving=true;this._status(autosave?'Autosave…':'Salvando…');try{const fn=autosave&&this._adapter.autosave?this._adapter.autosave.bind(this._adapter):this._adapter.saveDraft.bind(this._adapter);const result=await fn(this.document);this._dirty=false;this._status('Salvo');if(!autosave)this._notice('Rascunho salvo.');this.dispatchEvent(new CustomEvent('upb-save',{detail:{document:this.document,result},bubbles:true,composed:true}));return result;}catch(error){this._status('Não salvo');this._notice(error?.message||'Falha ao salvar.','error');throw error;}finally{this._saving=false;this._renderToolbar();}}
  async publish(){if(this._publishing)return;this._publishing=true;this._status('Publicando…');try{if(this._dirty)await this.save();const result=await this._adapter.publish(this.document);this._status('Publicado');this._notice('Página publicada.');this.dispatchEvent(new CustomEvent('upb-publish',{detail:{document:this.document,result},bubbles:true,composed:true}));return result;}catch(error){this._status('Falha na publicação');this._notice(error?.message||'Falha ao publicar.','error');throw error;}finally{this._publishing=false;this._renderToolbar();}}
  _renderAll(){if(!this._connected)return;this._renderToolbar();this._renderLeft();this._renderCanvas();this._renderInspector();}
  _renderToolbar(){const root=this.shadowRoot;const shell=root.querySelector('.shell');shell.classList.toggle('mobile-left',this._mobileDrawer==='left');shell.classList.toggle('mobile-right',this._mobileDrawer==='right');for(const el of root.querySelectorAll('[data-device]'))el.classList.toggle('active',el.dataset.device===this._device);root.querySelector('[data-action=undo]').disabled=!this._history.canUndo();root.querySelector('[data-action=redo]').disabled=!this._history.canRedo();root.querySelector('[data-action=save]').disabled=this._saving||!this._dirty;root.querySelector('[data-action=publish]').disabled=this._publishing;root.getElementById('canvas-frame').className=`canvas-frame ${this._device}`;root.getElementById('canvas-label').textContent=`${DEVICE_LABELS[this._device]} · ${this._device==='desktop'?'1180px':this._device==='tablet'?'820px':'390px'} · estilos responsivos`;for(const el of root.querySelectorAll('[data-left]'))el.classList.toggle('active',el.dataset.left===this._leftTab);for(const el of root.querySelectorAll('[data-right]'))el.classList.toggle('active',el.dataset.right===this._rightTab);}
  _renderLeft(){const host=this.shadowRoot.getElementById('left-panel');if(this._leftTab==='elements'){const groups=widgetGroups();let html=`<input class="search" data-role="widget-search" value="${esc(this._search)}" placeholder="Buscar elemento…">`;for(const [group,widgets] of Object.entries(groups)){const filtered=widgets.filter(w=>`${w.label} ${w.type}`.toLowerCase().includes(this._search.toLowerCase()));if(!filtered.length)continue;html+=`<div class="group-title">${esc(group)}</div><div class="widget-grid">${filtered.map(w=>`<div class="widget" draggable="true" data-widget-type="${esc(w.type)}"><span class="widget-icon">${esc(w.icon)}</span><span>${esc(w.label)}</span></div>`).join('')}</div>`;}host.innerHTML=html;return;}if(this._leftTab==='layers'){host.innerHTML=this._document.builder.root_ids.length?this._document.builder.root_ids.map(id=>this._layerHtml(id)).join(''):'<div class="responsive-note">A página ainda não possui elementos.</div>';return;}let html='<div class="group-title">Modelos incluídos</div>';html+=BUILTIN_TEMPLATES.map(t=>`<div class="template-card"><strong>${esc(t.name)}</strong><p>${esc(t.description)}</p><button class="btn" data-template-local="${esc(t.key)}">Aplicar modelo</button></div>`).join('');if(this._remoteTemplates.length){html+='<div class="group-title">Modelos do projeto</div>'+this._remoteTemplates.map(t=>`<div class="template-card"><strong>${esc(t.name||t.key)}</strong><p>${esc(t.description||'Modelo disponível no backend.')}</p><button class="btn" data-template-remote="${esc(t.key)}">Aplicar</button></div>`).join('');}host.innerHTML=html;}
  _layerHtml(id){const node=getNode(this._document,id);if(!node)return'';const def=widgetDefinition(node.type);return `<div class="layer ${this._selected===id?'active':''}" data-select-node="${esc(id)}"><span>${esc(def.icon)}</span><span>${esc(def.label)}</span><span class="layer-actions"><button class="mini" data-node-up="${esc(id)}" title="Subir">↑</button><button class="mini" data-node-down="${esc(id)}" title="Descer">↓</button></span></div>${node.children.length?`<div class="tree-indent">${node.children.map(child=>this._layerHtml(child)).join('')}</div>`:''}`;}
  _renderCanvas(){const preview=this.shadowRoot.getElementById('page-preview');const rendered=renderDocument(this._document,{device:this._device});preview.innerHTML=`<style>${rendered.css}</style>${rendered.html}`;if(!this._document.builder.root_ids.length)preview.innerHTML=`<style>${baseRenderCss(this._document.global_styles)}</style><div class="empty-canvas"><div><strong>Página vazia</strong>Arraste um elemento da esquerda ou aplique um modelo.</div></div>`;for(const el of preview.querySelectorAll('[data-upb-node]')){const id=el.getAttribute('data-upb-node');el.setAttribute('draggable','true');if(id===this._selected)el.classList.add('selected');const badge=document.createElement('span');badge.className='node-badge';badge.textContent=widgetDefinition(getNode(this._document,id)?.type||'').label;el.prepend(badge);}this.dispatchEvent(new CustomEvent('upb-preview-rendered',{detail:{root:preview,document:this.document,device:this._device},bubbles:true,composed:true}));}
  _renderInspector(){const head=this.shadowRoot.getElementById('inspector-head');const host=this.shadowRoot.getElementById('right-panel');const node=this._selected?getNode(this._document,this._selected):null;if(!node){head.innerHTML='<div class="inspector-title">Configurações da página</div><div class="inspector-sub">Identidade visual e SEO</div>';host.innerHTML=this._pageSettingsHtml();return;}const def=widgetDefinition(node.type);head.innerHTML=`<div class="inspector-title">${esc(def.label)}</div><div class="inspector-sub">${esc(node.type)} · ${esc(node.id)}</div>`;if(this._rightTab==='content'){host.innerHTML=this._contentInspector(node,def);return;}if(this._rightTab==='style'){host.innerHTML=this._styleInspector(node);return;}host.innerHTML=this._advancedInspector(node);}
  _contentInspector(node,def){let html='<div class="section"><h4>Conteúdo</h4>';for(const field of def.fields||[]){let value=node.props[field.key]??field.default??'';if(field.key==='images_text'&&!value&&Array.isArray(node.props.images))value=node.props.images.join('\n');if(field.key==='items_text'&&!value&&Array.isArray(node.props.items))value=node.props.items.map(item=>node.type==='faq'?`${item.question||item.title||''} | ${item.answer||item.text||''}`:`${item.name||item.title||''} | ${item.text||''}`).join('\n');if(field.control==='textarea')html+=`<div class="field"><label>${esc(field.label)}</label><textarea data-prop="${esc(field.key)}">${esc(Array.isArray(value)?JSON.stringify(value):value)}</textarea></div>`;else if(field.control==='select')html+=`<div class="field"><label>${esc(field.label)}</label><select data-prop="${esc(field.key)}">${field.options.map(([v,l])=>`<option value="${esc(v)}" ${String(value)===String(v)?'selected':''}>${esc(l)}</option>`).join('')}</select></div>`;else if(field.control==='toggle')html+=`<label class="check"><input type="checkbox" data-prop="${esc(field.key)}" ${value?'checked':''}> ${esc(field.label)}</label>`;else html+=`<div class="field"><label>${esc(field.label)}</label><input type="${field.control==='number'?'number':'text'}" data-prop="${esc(field.key)}" value="${esc(value)}" ${field.min!=null?`min="${field.min}"`:''} ${field.max!=null?`max="${field.max}"`:''}></div>`;}if(['image','logo','hero'].includes(node.type)&&this._adapter.upload)html+=`<div class="field"><label>Upload para o storage</label><input type="file" accept="image/*" data-upload-image></div>`;if(def.acceptsChildren)html+=`<div class="responsive-note">Este elemento aceita componentes filhos. Arraste novos elementos diretamente sobre ele no canvas.</div>`;return html+'</div>';}
  _effectiveStyle(node,key){if(this._device==='mobile'&&node.responsive.mobile?.[key]!=null)return node.responsive.mobile[key];if((this._device==='mobile'||this._device==='tablet')&&node.responsive.tablet?.[key]!=null)return node.responsive.tablet[key];return node.style?.[key]??'';}
  _styleInspector(node){const num=(key,label,min=-500,max=2400)=>`<div class="field"><label>${label}</label><input type="number" data-style="${key}" value="${esc(this._effectiveStyle(node,key))}" min="${min}" max="${max}"></div>`;const txt=(key,label)=>`<div class="field"><label>${label}</label><input type="text" data-style="${key}" value="${esc(this._effectiveStyle(node,key))}"></div>`;const sel=(key,label,options)=>`<div class="field"><label>${label}</label><select data-style="${key}"><option value="">Herdar / padrão</option>${options.map(([v,l])=>`<option value="${v}" ${String(this._effectiveStyle(node,key))===v?'selected':''}>${l}</option>`).join('')}</select></div>`;return `<div class="section"><h4>${DEVICE_LABELS[this._device]} · Aparência</h4><div class="responsive-note">Desktop define a base. Tablet e Mobile sobrescrevem apenas o que você alterar.</div><br><div class="field"><label>Cor do texto</label><div class="color-row"><input type="color" data-style-color="color" value="${this._colorValue(this._effectiveStyle(node,'color'),'#1d273a')}"><input data-style="color" value="${esc(this._effectiveStyle(node,'color'))}" placeholder="#1d273a"></div></div><div class="field"><label>Fundo</label><div class="color-row"><input type="color" data-style-color="backgroundColor" value="${this._colorValue(this._effectiveStyle(node,'backgroundColor'),'#ffffff')}"><input data-style="backgroundColor" value="${esc(this._effectiveStyle(node,'backgroundColor'))}" placeholder="#ffffff"></div></div><div class="field-row">${num('fontSize','Fonte',8,160)}${num('borderRadius','Raio',0,200)}</div><div class="field-row">${num('padding','Padding',0,300)}${num('margin','Margem',-300,300)}</div><div class="field-row">${num('gap','Gap',0,200)}${num('minHeight','Altura mínima',0,1600)}</div>${sel('textAlign','Alinhamento',[['left','Esquerda'],['center','Centro'],['right','Direita']])}${sel('flexDirection','Direção Flex',[['row','Horizontal'],['column','Vertical'],['row-reverse','Horizontal reverso'],['column-reverse','Vertical reverso']])}${sel('justifyContent','Distribuição',[['flex-start','Início'],['center','Centro'],['flex-end','Fim'],['space-between','Entre'],['space-around','Ao redor']])}${sel('alignItems','Alinhamento cruzado',[['stretch','Esticar'],['flex-start','Início'],['center','Centro'],['flex-end','Fim']])}${txt('maxWidth','Largura máxima (CSS)')}${txt('boxShadow','Sombra (CSS)')}</div>`;}
  _advancedInspector(node){const hidden=node.responsive.hidden||{};return `<div class="section"><h4>Responsividade</h4><div class="responsive-switch">${Object.entries(DEVICE_LABELS).map(([d,l])=>`<label class="check"><input type="checkbox" data-hidden="${d}" ${hidden[d]?'checked':''}> ${l}</label>`).join('')}</div></div><div class="section"><h4>Ações</h4><div class="field-row"><button class="btn" data-node-duplicate="${esc(node.id)}">Duplicar</button><button class="btn danger" data-node-delete="${esc(node.id)}">Excluir</button></div></div><div class="section"><h4>Metadados</h4><div class="field"><label>ID estável</label><input value="${esc(node.id)}" disabled></div><div class="field"><label>Classe CSS</label><input data-meta="cssClass" value="${esc(node.meta?.cssClass||'')}"></div><div class="field"><label>Âncora</label><input data-meta="anchor" value="${esc(node.meta?.anchor||'')}"></div></div>`;}
  _pageSettingsHtml(){const g=this._document.global_styles||{},seo=this._document.seo||{};const color=(key,label,fallback)=>`<div class="field"><label>${label}</label><div class="color-row"><input type="color" data-global-color="${key}" value="${this._colorValue(g[key],fallback)}"><input data-global="${key}" value="${esc(g[key]||fallback)}"></div></div>`;return `<div class="page-settings"><div class="section"><h4>Identidade visual</h4>${color('primary','Primária','#3151cf')}${color('secondary','Secundária','#151c31')}${color('accent','Destaque','#6d72ef')}${color('background','Fundo','#ffffff')}${color('text','Texto','#1d273a')}<div class="field"><label>Fonte de títulos</label><input data-global="heading_font" value="${esc(g.heading_font||'Inter')}"></div><div class="field"><label>Fonte do corpo</label><input data-global="body_font" value="${esc(g.body_font||'Inter')}"></div><div class="field"><label>Raio global</label><input type="number" min="0" max="60" data-global="radius" value="${esc(g.radius||16)}"></div></div><div class="section"><h4>SEO</h4><div class="field"><label>Título</label><input data-seo="title" value="${esc(seo.title||'')}"></div><div class="field"><label>Descrição</label><textarea data-seo="description">${esc(seo.description||'')}</textarea></div><div class="field"><label>Imagem de compartilhamento</label><input data-seo="share_image" value="${esc(seo.share_image||'')}"></div></div></div>`;}
  _colorValue(value,fallback){const raw=String(value||'');return /^#[0-9a-f]{6}$/i.test(raw)?raw:fallback;}
  _onClick(event){const t=event.target.closest?.('button,[data-select-node],[data-upb-node],[data-widget-type],[data-action]');if(!t)return;if(t.dataset.widgetType){const type=t.dataset.widgetType;let parentId=null;if(this._selected){const selected=getNode(this._document,this._selected);if(widgetDefinition(selected?.type).acceptsChildren)parentId=selected.id;}const n=createNode(type,createProps(type));addNode(this._document,n,parentId);this._selected=n.id;if(innerWidth<=760)this._mobileDrawer='right';this._mutated();return;}if(t.dataset.device){this._device=t.dataset.device;this._renderAll();return;}if(t.dataset.left){this._leftTab=t.dataset.left;this._renderAll();return;}if(t.dataset.right){this._rightTab=t.dataset.right;this._renderAll();return;}if(t.dataset.selectNode){this._selected=t.dataset.selectNode;if(innerWidth<=760)this._mobileDrawer='right';this._renderAll();return;}if(t.matches('[data-upb-node]')||t.closest('[data-upb-node]')){const nodeEl=t.matches('[data-upb-node]')?t:t.closest('[data-upb-node]');this._selected=nodeEl.dataset.upbNode;if(innerWidth<=760)this._mobileDrawer='right';this._renderAll();return;}const a=t.dataset.action;if(a){if(a==='undo')this._undo();else if(a==='redo')this._redo();else if(a==='save')void this.save();else if(a==='publish')void this.publish();else if(a==='import')this.shadowRoot.getElementById('import-file').click();else if(a==='export-json')download(`${this._slugName()}.json`,JSON.stringify(this.document,null,2));else if(a==='export-html')download(`${this._slugName()}.html`,exportStandaloneHtml(this.document),'text/html');else if(a==='preview')this._previewWindow();else if(a==='mobile-left'){this._mobileDrawer=this._mobileDrawer==='left'?null:'left';this._renderToolbar();}else if(a==='mobile-right'){this._mobileDrawer=this._mobileDrawer==='right'?null:'right';this._renderToolbar();}else if(a==='mobile-close'){this._mobileDrawer=null;this._renderToolbar();}else if(a==='close')this.dispatchEvent(new CustomEvent('upb-close',{bubbles:true,composed:true}));return;}if(t.dataset.templateLocal){const tpl=BUILTIN_TEMPLATES.find(x=>x.key===t.dataset.templateLocal);if(tpl)this._replaceDocument(tpl.create(),'Modelo aplicado.');return;}if(t.dataset.templateRemote){void this._applyRemoteTemplate(t.dataset.templateRemote);return;}if(t.dataset.nodeDuplicate){const copy=duplicateNode(this._document,t.dataset.nodeDuplicate);if(copy){this._selected=copy.id;this._mutated();}return;}if(t.dataset.nodeDelete){this._deleteNode(t.dataset.nodeDelete);return;}if(t.dataset.nodeUp){this._moveSibling(t.dataset.nodeUp,-1);return;}if(t.dataset.nodeDown){this._moveSibling(t.dataset.nodeDown,1);return;}}
  _onInput(event){const el=event.target;if(el.dataset.role==='widget-search'){this._search=el.value;this._renderLeft();return;}this._applyField(el,false);}
  _onChange(event){const el=event.target;if(el.matches('[data-upload-image]')){void this._uploadImage(el);return;}this._applyField(el,true);}
  _applyField(el,commit){const node=this._selected?getNode(this._document,this._selected):null;let changed=false;if(node&&el.dataset.prop){const def=widgetDefinition(node.type).fields?.find(f=>f.key===el.dataset.prop);node.props[el.dataset.prop]=el.type==='checkbox'?el.checked:def?.control==='number'?toNumber(el.value):el.value;changed=true;}if(node&&el.dataset.style){const target=this._device==='desktop'?node.style:node.responsive[this._device];if(el.value==='')delete target[el.dataset.style];else target[el.dataset.style]=['fontSize','borderRadius','padding','margin','gap','minHeight'].includes(el.dataset.style)?toNumber(el.value):el.value;changed=true;}if(node&&el.dataset.styleColor){const key=el.dataset.styleColor;const target=this._device==='desktop'?node.style:node.responsive[this._device];target[key]=el.value;changed=true;this._syncSiblingInput(el,`[data-style="${key}"]`);}if(node&&el.dataset.hidden){node.responsive.hidden[el.dataset.hidden]=el.checked;changed=true;}if(node&&el.dataset.meta){node.meta=node.meta||{};node.meta[el.dataset.meta]=el.value;changed=true;}if(el.dataset.global){this._document.global_styles[el.dataset.global]=el.type==='number'?toNumber(el.value):el.value;changed=true;}if(el.dataset.globalColor){this._document.global_styles[el.dataset.globalColor]=el.value;changed=true;this._syncSiblingInput(el,`[data-global="${el.dataset.globalColor}"]`);}if(el.dataset.seo){this._document.seo[el.dataset.seo]=el.value;changed=true;}if(changed){this._mutated(null,{renderInspector:commit});}}
  _syncSiblingInput(el,selector){const parent=el.parentElement;const other=parent?.querySelector(selector);if(other)other.value=el.value;}
  _onDragStart(event){const widget=event.target.closest?.('[data-widget-type]');if(widget){event.dataTransfer.effectAllowed='copy';event.dataTransfer.setData('application/x-upb-widget',widget.dataset.widgetType);this.shadowRoot.getElementById('canvas-frame').classList.add('dragging');return;}const nodeEl=event.target.closest?.('[data-upb-node]');if(nodeEl){event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('application/x-upb-node',nodeEl.dataset.upbNode);this.shadowRoot.getElementById('canvas-frame').classList.add('dragging');}}
  _onDragOver(event){if(event.target.closest?.('#page-preview,[data-drop-root]')){event.preventDefault();event.dataTransfer.dropEffect=event.dataTransfer.types.includes('application/x-upb-widget')?'copy':'move';}}
  _onDrop(event){event.preventDefault();this.shadowRoot.getElementById('canvas-frame').classList.remove('dragging');const widgetType=event.dataTransfer.getData('application/x-upb-widget');const moveId=event.dataTransfer.getData('application/x-upb-node');const targetEl=event.target.closest?.('[data-upb-node]');let parentId=null,index=null;if(targetEl){const targetId=targetEl.dataset.upbNode;const target=getNode(this._document,targetId);if(widgetDefinition(target?.type).acceptsChildren){parentId=targetId;}else{const parent=parentOf(this._document,targetId);parentId=parent?.id||null;const list=parent?parent.children:this._document.builder.root_ids;index=list.indexOf(targetId)+1;}}if(widgetType){const n=createNode(widgetType,createProps(widgetType));addNode(this._document,n,parentId,index);this._selected=n.id;this._mutated();return;}if(moveId&&getNode(this._document,moveId)){if(moveNode(this._document,moveId,parentId,index)){this._selected=moveId;this._mutated();}}}
  _moveSibling(id,delta){const parent=parentOf(this._document,id);const list=parent?parent.children:this._document.builder.root_ids;const from=list.indexOf(id),to=from+delta;if(from<0||to<0||to>=list.length)return;list.splice(to,0,list.splice(from,1)[0]);this._mutated();}
  _deleteNode(id){if(!getNode(this._document,id))return;removeNode(this._document,id);this._selected=this._document.builder.root_ids[0]||null;this._mutated();}
  _replaceDocument(value,message=null){this._document=normalizeDocument(value);this._selected=this._document.builder.root_ids[0]||null;this._dirty=true;this._history.checkpoint(this._document);this._renderAll();this._scheduleAutosave();if(message)this._notice(message);this.dispatchEvent(new CustomEvent('upb-change',{detail:{document:this.document},bubbles:true,composed:true}));}
  _mutated(message=null,{renderInspector=true}={}){this._dirty=true;this._history.checkpoint(this._document);this._renderToolbar();this._renderLeft();this._renderCanvas();if(renderInspector)this._renderInspector();this._scheduleAutosave();if(message)this._notice(message);this.dispatchEvent(new CustomEvent('upb-change',{detail:{document:this.document},bubbles:true,composed:true}));}
  _undo(){if(!this._history.canUndo())return;this._document=normalizeDocument(this._history.undo());if(this._selected&&!getNode(this._document,this._selected))this._selected=this._document.builder.root_ids[0]||null;this._dirty=true;this._renderAll();this._scheduleAutosave();}
  _redo(){if(!this._history.canRedo())return;this._document=normalizeDocument(this._history.redo());this._dirty=true;this._renderAll();this._scheduleAutosave();}
  _onKeyboard(event){if(!this.isConnected)return;const active=this.shadowRoot.activeElement;const typing=active&&['INPUT','TEXTAREA','SELECT'].includes(active.tagName);if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'){event.preventDefault();event.shiftKey?this._redo():this._undo();}else if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='y'){event.preventDefault();this._redo();}else if(!typing&&event.key==='Delete'&&this._selected){event.preventDefault();this._deleteNode(this._selected);}}
  _scheduleAutosave(){if(!this._adapter?.autosave)return;if(this._autosaveTimer)clearTimeout(this._autosaveTimer);this._autosaveTimer=setTimeout(()=>{if(this._dirty&&!this._saving&&!this._publishing)void this.save({autosave:true}).catch(()=>{});},1300);}
  async _importFile(event){const file=event.target.files?.[0];event.target.value='';if(!file)return;try{const json=JSON.parse(await file.text());this._replaceDocument(json,'Documento importado.');}catch(error){this._notice(`Arquivo inválido: ${error?.message||error}`,'error');}}
  async _uploadImage(input){const file=input.files?.[0];if(!file||!this._selected)return;try{this._status('Enviando imagem…');const url=await this._adapter.upload(file);const node=getNode(this._document,this._selected);if(node){node.props.image=url;this._mutated('Imagem enviada.');}}catch(error){this._notice(error?.message||'Falha no upload.','error');}finally{input.value='';this._status('');}}
  async _applyRemoteTemplate(key){if(!this._adapter.applyTemplate)return;try{this._status('Aplicando modelo…');await this._adapter.applyTemplate(key);await this.load();this._notice('Modelo aplicado.');}catch(error){this._notice(error?.message||'Falha ao aplicar modelo.','error');}finally{this._status('');}}
  _previewWindow(){const html=exportStandaloneHtml(this.document);const url=URL.createObjectURL(new Blob([html],{type:'text/html'}));window.open(url,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(url),60000);}
  _slugName(){return String(this._document.title||'landing-page').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'landing-page';}
  _status(text){const el=this.shadowRoot?.getElementById('save-status');if(el)el.innerHTML=text?`<span class="status-dot"></span>${esc(text)}`:'';}
  _notice(message,type='success'){const host=this.shadowRoot.getElementById('notice-host');host.innerHTML=`<div class="notice ${type==='error'?'error':''}">${esc(message)}</div>`;setTimeout(()=>{if(host.textContent===String(message))host.innerHTML='';},3500);}
}
if(globalThis.customElements && !customElements.get('argws-visual-builder'))customElements.define('argws-visual-builder',ArgwsVisualBuilder);
