export function createEmbedSnippet(target='html', { moduleUrl='/vendor/argws-visual-builder/src/index.js', cssUrl='/vendor/argws-visual-builder/styles/builder.css', documentUrl='/api/pages/home', editor=false, elementId='argws-page' } = {}) {
  const tag=editor?'argws-visual-builder':'argws-page-renderer';
  const js=`import '${moduleUrl}';\nconst el=document.getElementById('${elementId}');\nconst response=await fetch('${documentUrl}',{headers:{Accept:'application/json'}});\nconst payload=await response.json();\nel.document=payload.data?.document||payload.document||payload;`;
  if(target==='blade')return `<link rel="stylesheet" href="{{ asset('${cssUrl.replace(/^\//,'')}') }}">\n<${tag} id="${elementId}"></${tag}>\n<script type="module">${js.replace(moduleUrl,`{{ asset('${moduleUrl.replace(/^\//,'')}') }}`)}</script>`;
  if(target==='php')return `<link rel="stylesheet" href="<?= htmlspecialchars('${cssUrl}', ENT_QUOTES) ?>">\n<${tag} id="${elementId}"></${tag}>\n<script type="module">${js}</script>`;
  if(target==='jinja2')return `<link rel="stylesheet" href="{{ url_for('static', path='${cssUrl.replace(/^\//,'')}') }}">\n<${tag} id="${elementId}"></${tag}>\n<script type="module">${js}</script>`;
  if(target==='twig')return `<link rel="stylesheet" href="{{ asset('${cssUrl.replace(/^\//,'')}') }}">\n<${tag} id="${elementId}"></${tag}>\n<script type="module">${js}</script>`;
  if(target==='vue')return `<template><${tag} ref="host" /></template>\n<script setup>\nimport {onMounted,ref} from 'vue';\nimport '@argws/visual-builder';\nimport '@argws/visual-builder/styles.css';\nconst host=ref();\nonMounted(async()=>{const r=await fetch('${documentUrl}');const p=await r.json();host.value.document=p.data?.document||p.document||p;});\n</script>`;
  if(target==='react')return `import {useEffect,useRef} from 'react';\nimport '@argws/visual-builder';\nimport '@argws/visual-builder/styles.css';\nexport default function ArgwsPage(){const ref=useRef(null);useEffect(()=>{fetch('${documentUrl}').then(r=>r.json()).then(p=>{ref.current.document=p.data?.document||p.document||p;});},[]);return <${tag} ref={ref}></${tag}>;}`;
  if(target==='svelte')return `<script>import '@argws/visual-builder';import '@argws/visual-builder/styles.css';import {onMount} from 'svelte';let host;onMount(async()=>{const r=await fetch('${documentUrl}');const p=await r.json();host.document=p.data?.document||p.document||p;});</script><${tag} bind:this={host}></${tag}>`;
  return `<link rel="stylesheet" href="${cssUrl}">\n<${tag} id="${elementId}"></${tag}>\n<script type="module">${js}</script>`;
}
