[package]
name = "scheduler_pro_desktop"
version = "2.0.1"
description = "Scheduler Pro Desktop baseado no template Tauri/Rust"
authors = ["Wallace Kleiton <wkarts@gmail.com>"]
edition = "2021"

[lib]
name = "scheduler_pro_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[features]
default = ["desktop"]
desktop = ["tauri/wry", "tauri/tray-icon", "tauri/image-png", "tauri/custom-protocol"]
mobile = ["tauri/wry", "tauri/custom-protocol"]

[dependencies]
tauri = { version = "2", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
