<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { Bell, CalendarClock, CalendarDays, Download, Globe2, LayoutDashboard, Link2, LogOut, Menu, MessageCircle, MonitorSmartphone, PackageCheck, Palette, Plus, Search, Settings, Smartphone, UserRoundCheck, Users, Wrench } from 'lucide-vue-next'
import { applyBranding, loadBrandingManifest, type BrandingManifest } from './branding'

type ViewKey = 'dashboard' | 'agenda' | 'clientes' | 'servicos' | 'profissionais' | 'landing' | 'whatsapp' | 'branding' | 'dominios' | 'builds' | 'configuracoes'
type InstallPromptEvent = Event & { prompt: () => Promise<void>; userChoice: Promise<{ outcome: 'accepted' | 'dismissed'; platform: string }> }
type ApiEnvelope<T> = { data: T }
type Appointment = { id:string;customer_id:string;service_id:string;professional_id:string;starts_at:string;ends_at:string;status:string;customer_name:string;service_name:string;professional_name:string }
type Customer = { id:string;name:string;phone?:string|null;email?:string|null;notes?:string|null }
type Service = { id:string;name:string;duration_minutes:number;price?:number|null;active:boolean }
type Professional = { id:string;name:string;email?:string|null;phone?:string|null }
type NotificationJob = { id:string;template_key:string;recipient:string;scheduled_at:string;status:string;error?:string|null }
type TenantSettings = { tenant_id:string;slug:string;hostname:string;timezone:string;preferences:Record<string,unknown> }

const navItems = [
  { key:'dashboard',label:'Visão geral',icon:LayoutDashboard },{ key:'agenda',label:'Agenda',icon:CalendarDays },{ key:'clientes',label:'Clientes',icon:Users },{ key:'servicos',label:'Serviços',icon:Wrench },{ key:'profissionais',label:'Profissionais',icon:UserRoundCheck },{ key:'landing',label:'Landing page',icon:Globe2 },{ key:'whatsapp',label:'WhatsApp API',icon:MessageCircle },{ key:'branding',label:'Marca e aplicativo',icon:Palette },{ key:'dominios',label:'Domínio e distribuição',icon:Link2 },{ key:'builds',label:'Aplicativos',icon:PackageCheck },{ key:'configuracoes',label:'Configurações',icon:Settings },
] as const

const view=ref<ViewKey>(hashToView());const collapsed=ref(false);const mobileOpen=ref(false);const manifest=ref<BrandingManifest|null>(null);const apiStatus=ref<'connected'|'fallback'>('fallback');const installPrompt=ref<InstallPromptEvent|null>(null);const installing=ref(false)
const email=ref(localStorage.getItem('scheduler_pro_email')||'');const password=ref('');const authError=ref('');const actionError=ref('');const toast=ref('');const token=ref(localStorage.getItem('scheduler_pro_access_token')||'');const logged=computed(()=>Boolean(token.value));const loading=ref(false)
const appointments=ref<Appointment[]>([]);const customers=ref<Customer[]>([]);const services=ref<Service[]>([]);const professionals=ref<Professional[]>([]);const notifications=ref<NotificationJob[]>([]);const tenantSettings=ref<TenantSettings|null>(null);const whatsapp=ref<Record<string,unknown>>({});const showForm=ref(false)
const appointmentForm=ref({customer_id:'',service_id:'',professional_id:'',starts_at:'',ends_at:''});const customerForm=ref({name:'',phone:'',email:'',notes:''});const serviceForm=ref({name:'',duration_minutes:30,price:null as number|null,active:true});const professionalForm=ref({name:'',email:'',phone:''});const messageForm=ref({to:'',message:''});const landingForm=ref({title:'Agende seu atendimento',subtitle:'Escolha o melhor horário para você.',cta:'Agendar agora'});const brandingForm=ref({public_name:'',slogan:'',primary_color:'#2563eb',accent_color:'#0ea5e9',theme_mode:'system'});const settingForm=ref({key:'',value:''})
const browserHostname=window.location.hostname

const appName=computed(()=>manifest.value?.app?.public_name||manifest.value?.app?.name||'Scheduler Pro');const slogan=computed(()=>manifest.value?.app?.slogan||'Plataforma inteligente de agendamentos');const activeTitle=computed(()=>navItems.find(i=>i.key===view.value)?.label||'Visão geral');const isStandalone=computed(()=>window.matchMedia('(display-mode: standalone)').matches||Boolean((window.navigator as Navigator&{standalone?:boolean}).standalone));const todayAppointments=computed(()=>appointments.value.length);const confirmedToday=computed(()=>appointments.value.filter(i=>i.status==='CONFIRMED').length);const pendingToday=computed(()=>appointments.value.filter(i=>['PENDING','AWAITING_CONFIRMATION','RESCHEDULED'].includes(i.status)).length)

function apiBase():string{return `${window.location.origin}/api/v1`}function hashToView():ViewKey{const current=(window.location.hash||'#dashboard').replace('#','');return navItems.some(i=>i.key===current)?current as ViewKey:'dashboard'}function go(key:ViewKey):void{view.value=key;mobileOpen.value=false;showForm.value=false;actionError.value='';if(window.location.hash!==`#${key}`)history.replaceState(null,'',`#${key}`)}function onHashChange():void{view.value=hashToView()}function onBeforeInstallPrompt(event:Event):void{event.preventDefault();installPrompt.value=event as InstallPromptEvent}function showToast(message:string):void{toast.value=message;window.setTimeout(()=>{if(toast.value===message)toast.value=''},3500)}
async function installWebApp():Promise<void>{if(!installPrompt.value)return;installing.value=true;try{await installPrompt.value.prompt();await installPrompt.value.userChoice;installPrompt.value=null}finally{installing.value=false}}
async function api<T>(path:string,init:RequestInit={}):Promise<T>{let response:Response;try{response=await fetch(`${apiBase()}${path}`,{...init,headers:{...(init.body instanceof FormData?{}:{'content-type':'application/json'}),...(token.value?{authorization:`Bearer ${token.value}`}:{ }),...(init.headers||{})}})}catch{throw new Error('Não foi possível conectar à API.')}const body=await response.json().catch(()=>({})) as Partial<ApiEnvelope<T>>&{error?:{message?:string}};if(!response.ok)throw new Error(body.error?.message||`Falha HTTP ${response.status}`);return body.data as T}
async function loadBranding():Promise<void>{try{const data=await loadBrandingManifest();manifest.value=data;applyBranding(data);brandingForm.value={public_name:data.app.public_name,slogan:data.app.slogan||'',primary_color:data.theme.colors.primary,accent_color:data.theme.colors.accent,theme_mode:data.theme.mode};apiStatus.value='connected'}catch{apiStatus.value='fallback'}}
async function login():Promise<void>{authError.value='';loading.value=true;try{const data=await api<{access_token:string;refresh_token:string}>('/auth/login',{method:'POST',body:JSON.stringify({email:email.value,password:password.value})});token.value=data.access_token;localStorage.setItem('scheduler_pro_access_token',data.access_token);localStorage.setItem('scheduler_pro_refresh_token',data.refresh_token);localStorage.setItem('scheduler_pro_email',email.value);password.value='';await syncAll();go('dashboard')}catch(error){authError.value=error instanceof Error?error.message:'Login inválido'}finally{loading.value=false}}
function logout():void{token.value='';localStorage.removeItem('scheduler_pro_access_token');localStorage.removeItem('scheduler_pro_refresh_token')}
async function syncAll():Promise<void>{if(!token.value)return;loading.value=true;actionError.value='';try{const[a,c,s,p,n,ts]=await Promise.all([api<Appointment[]>('/appointments'),api<Customer[]>('/customers'),api<Service[]>('/services'),api<Professional[]>('/professionals'),api<NotificationJob[]>('/notifications?limit=100').catch(()=>[]),api<TenantSettings>('/settings/tenant').catch(()=>null)]);appointments.value=a;customers.value=c;services.value=s;professionals.value=p;notifications.value=n;tenantSettings.value=ts;try{whatsapp.value=await api('/integrations/whatsapp/status')}catch{whatsapp.value={status:'DISCONNECTED'}};apiStatus.value='connected'}catch(error){actionError.value=error instanceof Error?error.message:'Falha na sincronização';apiStatus.value='fallback'}finally{loading.value=false}}
async function createAppointment():Promise<void>{try{await api('/appointments',{method:'POST',body:JSON.stringify({...appointmentForm.value,starts_at:new Date(appointmentForm.value.starts_at).toISOString(),ends_at:new Date(appointmentForm.value.ends_at).toISOString(),source:'web'})});appointmentForm.value={customer_id:'',service_id:'',professional_id:'',starts_at:'',ends_at:''};showForm.value=false;appointments.value=await api('/appointments');showToast('Agendamento criado.')}catch(e){actionError.value=e instanceof Error?e.message:'Falha ao agendar.'}}
async function appointmentAction(id:string,action:string):Promise<void>{try{await api(`/appointments/${id}/${action}`,{method:'POST',body:'{}'});appointments.value=await api('/appointments');showToast('Agendamento atualizado.')}catch(e){actionError.value=e instanceof Error?e.message:'Falha ao atualizar.'}}
async function cancelAppointment(id:string):Promise<void>{try{await api(`/appointments/${id}/cancel`,{method:'POST',body:JSON.stringify({reason:'Cancelado pelo painel'})});appointments.value=await api('/appointments');showToast('Cancelado.')}catch(e){actionError.value=e instanceof Error?e.message:'Falha ao cancelar.'}}
async function createCustomer():Promise<void>{try{await api('/customers',{method:'POST',body:JSON.stringify({...customerForm.value,email:customerForm.value.email||null,phone:customerForm.value.phone||null,notes:customerForm.value.notes||null})});customerForm.value={name:'',phone:'',email:'',notes:''};showForm.value=false;customers.value=await api('/customers');showToast('Cliente cadastrado.')}catch(e){actionError.value=e instanceof Error?e.message:'Falha ao cadastrar.'}}
async function createService():Promise<void>{try{await api('/services',{method:'POST',body:JSON.stringify(serviceForm.value)});serviceForm.value={name:'',duration_minutes:30,price:null,active:true};showForm.value=false;services.value=await api('/services');showToast('Serviço cadastrado.')}catch(e){actionError.value=e instanceof Error?e.message:'Falha ao cadastrar.'}}
async function createProfessional():Promise<void>{try{await api('/professionals',{method:'POST',body:JSON.stringify({...professionalForm.value,email:professionalForm.value.email||null,phone:professionalForm.value.phone||null})});professionalForm.value={name:'',email:'',phone:''};showForm.value=false;professionals.value=await api('/professionals');showToast('Profissional cadastrado.')}catch(e){actionError.value=e instanceof Error?e.message:'Falha ao cadastrar.'}}
async function connectWhatsApp():Promise<void>{try{whatsapp.value=await api('/integrations/whatsapp/connect',{method:'POST',body:'{}'});showToast('Conexão iniciada.')}catch(e){actionError.value=e instanceof Error?e.message:'Falha no WhatsApp.'}}
async function sendMessage():Promise<void>{try{await api('/integrations/whatsapp/send-text',{method:'POST',body:JSON.stringify(messageForm.value)});messageForm.value.message='';showToast('Mensagem enviada.')}catch(e){actionError.value=e instanceof Error?e.message:'Falha no envio.'}}
async function saveLanding(publish=false):Promise<void>{try{await api('/landing-pages/home/draft',{method:'POST',body:JSON.stringify({version:1,sections:[{type:'hero',title:landingForm.value.title,subtitle:landingForm.value.subtitle,cta:landingForm.value.cta},{type:'booking',enabled:true}]})});if(publish)await api('/landing-pages/home/publish',{method:'POST',body:'{}'});showToast(publish?'Landing publicada.':'Rascunho salvo.')}catch(e){actionError.value=e instanceof Error?e.message:'Falha na landing.'}}
async function saveBranding(publish=false):Promise<void>{try{await api('/branding/profile',{method:'PUT',body:JSON.stringify(brandingForm.value)});if(publish)await api('/branding/publish',{method:'POST',body:'{}'});await loadBranding();showToast(publish?'Marca publicada.':'Marca salva.')}catch(e){actionError.value=e instanceof Error?e.message:'Falha na marca.'}}
async function saveSetting():Promise<void>{try{let value:unknown=settingForm.value.value;try{value=JSON.parse(settingForm.value.value)}catch{value=settingForm.value.value}await api(`/settings/tenant/${encodeURIComponent(settingForm.value.key)}`,{method:'PUT',body:JSON.stringify(value)});tenantSettings.value=await api('/settings/tenant');settingForm.value={key:'',value:''};showToast('Configuração salva.')}catch(e){actionError.value=e instanceof Error?e.message:'Falha na configuração.'}}
function desktopInstructions():string{return `O Desktop carrega ${window.location.origin} diretamente. Alterações publicadas no WebApp aparecem no aplicativo sem duplicar a interface.`}

onMounted(()=>{loadBranding();syncAll();window.addEventListener('hashchange',onHashChange);window.addEventListener('beforeinstallprompt',onBeforeInstallPrompt)});onUnmounted(()=>{window.removeEventListener('hashchange',onHashChange);window.removeEventListener('beforeinstallprompt',onBeforeInstallPrompt)})
</script>

<template>
<section v-if="!logged" class="auth-page"><aside class="auth-visual"><div class="auth-brand"><div class="brand-mark"><CalendarClock :size="28"/></div><div><strong>{{appName}}</strong><span>{{slogan}}</span></div></div><h1>Agendamentos, clientes e confirmação por WhatsApp em uma plataforma escalável.</h1><p>Acesse o painel da empresa para administrar toda a operação.</p></aside><form class="auth-card" @submit.prevent="login"><h2>Entrar na plataforma</h2><p>Acesse o painel gerencial da sua empresa.</p><label>E-mail<input v-model="email" type="email" autocomplete="username" required/></label><label>Senha<input v-model="password" type="password" autocomplete="current-password" required/></label><p v-if="authError" class="form-error">{{authError}}</p><button class="btn primary full" :disabled="loading">{{loading?'Entrando...':'Entrar'}}</button><button v-if="installPrompt&&!isStandalone" class="btn full" type="button" @click="installWebApp">Instalar web app</button></form></section>

<div v-else class="app-shell" :class="{collapsed,mobileOpen}"><aside class="sidebar"><div class="brand"><div class="brand-mark"><CalendarClock :size="24"/></div><div v-if="!collapsed"><strong>{{appName}}</strong><small>{{slogan}}</small></div></div><nav class="nav-list"><button v-for="item in navItems" :key="item.key" class="nav-item" :class="{active:view===item.key}" @click="go(item.key)"><component :is="item.icon" :size="19"/><span v-if="!collapsed">{{item.label}}</span></button></nav><div class="sidebar-footer"><button v-if="installPrompt&&!isStandalone" class="nav-item" @click="installWebApp"><Download :size="19"/><span v-if="!collapsed">Instalar web app</span></button><button class="nav-item" @click="logout"><LogOut :size="19"/><span v-if="!collapsed">Sair</span></button><div v-if="!collapsed" class="version-info"><strong>Scheduler Pro</strong><small>{{apiStatus==='connected'?'API conectada':'API indisponível'}}</small></div></div></aside>
<div class="content-shell"><header class="topbar"><button class="icon-button" @click="collapsed=!collapsed;mobileOpen=!mobileOpen"><Menu :size="20"/></button><label class="company-switcher"><span>Empresa ativa</span><strong>{{appName}}</strong></label><div class="topbar-search"><Search :size="17"/><input placeholder="Buscar na operação"/></div><div class="topbar-spacer"></div><button v-if="installPrompt&&!isStandalone" class="btn install-top" @click="installWebApp"><Smartphone :size="16"/> Instalar</button><button class="icon-button notification"><Bell :size="20"/><i></i></button><div class="profile"><div class="avatar">{{email.slice(0,1).toUpperCase()||'SP'}}</div><div><strong>{{email}}</strong><small>Gestor</small></div></div></header>
<main class="main-content"><section class="page-header"><div><p class="eyebrow">Scheduler Pro</p><h1>{{activeTitle}}</h1><p>Operação conectada ao banco exclusivo do tenant.</p></div><div class="page-actions"><button class="btn" @click="syncAll">Atualizar</button><button v-if="['agenda','clientes','servicos','profissionais'].includes(view)" class="btn primary" @click="showForm=!showForm"><Plus :size="16"/> {{showForm?'Fechar':'Novo'}}</button></div></section><p v-if="toast" class="success-banner">{{toast}}</p><p v-if="actionError" class="error-banner">{{actionError}}</p>

<section v-if="view==='dashboard'" class="view-stack"><div class="metric-grid"><article class="metric-card blue"><div><span>Agendamentos</span><strong>{{todayAppointments}}</strong><small>{{confirmedToday}} confirmados • {{pendingToday}} pendentes</small></div><CalendarDays/></article><article class="metric-card green"><div><span>Clientes</span><strong>{{customers.length}}</strong><small>cadastros ativos</small></div><Users/></article><article class="metric-card orange"><div><span>Notificações</span><strong>{{notifications.filter(n=>n.status==='PENDING').length}}</strong><small>jobs pendentes</small></div><MessageCircle/></article></div><section class="panel"><div class="panel-title"><div><h3>Próximos atendimentos</h3><p>Agenda real do tenant</p></div></div><div class="table-like"><article v-for="item in appointments.slice(0,12)" :key="item.id"><time>{{new Date(item.starts_at).toLocaleString()}}</time><div><strong>{{item.customer_name}}</strong><small>{{item.service_name}} • {{item.professional_name}}</small></div><span class="status-pill">{{item.status}}</span></article><p v-if="!appointments.length" class="empty-state">Nenhum agendamento.</p></div></section></section>

<section v-else-if="view==='agenda'" class="view-stack"><form v-if="showForm" class="panel operational-form" @submit.prevent="createAppointment"><h3>Novo agendamento</h3><div class="form-grid"><select v-model="appointmentForm.customer_id" required><option value="">Cliente</option><option v-for="c in customers" :key="c.id" :value="c.id">{{c.name}}</option></select><select v-model="appointmentForm.service_id" required><option value="">Serviço</option><option v-for="s in services.filter(s=>s.active)" :key="s.id" :value="s.id">{{s.name}}</option></select><select v-model="appointmentForm.professional_id" required><option value="">Profissional</option><option v-for="p in professionals" :key="p.id" :value="p.id">{{p.name}}</option></select><label>Início<input v-model="appointmentForm.starts_at" type="datetime-local" required/></label><label>Fim<input v-model="appointmentForm.ends_at" type="datetime-local" required/></label></div><button class="btn primary">Salvar</button></form><section class="panel"><div class="data-table operational"><div class="table-head"><span>Horário</span><span>Cliente / serviço</span><span>Status</span><span>Ações</span></div><div v-for="a in appointments" :key="a.id" class="table-row"><span>{{new Date(a.starts_at).toLocaleString()}}</span><span><strong>{{a.customer_name}}</strong><small>{{a.service_name}} • {{a.professional_name}}</small></span><span class="status-pill">{{a.status}}</span><span class="actions"><button v-if="['PENDING','AWAITING_CONFIRMATION','RESCHEDULED'].includes(a.status)" class="btn small" @click="appointmentAction(a.id,'confirm')">Confirmar</button><button v-if="a.status==='CONFIRMED'" class="btn small" @click="appointmentAction(a.id,'check-in')">Check-in</button><button v-if="a.status==='CHECKED_IN'" class="btn small" @click="appointmentAction(a.id,'start')">Iniciar</button><button v-if="a.status==='IN_PROGRESS'" class="btn small" @click="appointmentAction(a.id,'complete')">Concluir</button><button v-if="!['COMPLETED','CANCELLED','NO_SHOW'].includes(a.status)" class="btn small danger" @click="cancelAppointment(a.id)">Cancelar</button></span></div></div></section></section>

<section v-else-if="view==='clientes'" class="view-stack"><form v-if="showForm" class="panel operational-form" @submit.prevent="createCustomer"><h3>Novo cliente</h3><div class="form-grid"><input v-model="customerForm.name" placeholder="Nome" required/><input v-model="customerForm.phone" placeholder="Telefone"/><input v-model="customerForm.email" type="email" placeholder="E-mail"/><textarea v-model="customerForm.notes" placeholder="Observações"></textarea></div><button class="btn primary">Cadastrar</button></form><section class="entity-grid"><article v-for="c in customers" :key="c.id" class="entity-card"><div class="entity-avatar">{{c.name.slice(0,1).toUpperCase()}}</div><div><strong>{{c.name}}</strong><small>{{c.phone||c.email||'Sem contato'}}</small><p>{{c.notes||''}}</p></div></article></section></section>

<section v-else-if="view==='servicos'" class="view-stack"><form v-if="showForm" class="panel operational-form" @submit.prevent="createService"><h3>Novo serviço</h3><div class="form-grid"><input v-model="serviceForm.name" placeholder="Nome" required/><input v-model.number="serviceForm.duration_minutes" type="number" min="5" max="720" placeholder="Duração"/><input v-model.number="serviceForm.price" type="number" min="0" step="0.01" placeholder="Preço"/></div><button class="btn primary">Cadastrar</button></form><section class="entity-grid"><article v-for="s in services" :key="s.id" class="entity-card"><Wrench/><div><strong>{{s.name}}</strong><small>{{s.duration_minutes}} min • {{s.price!=null?`R$ ${s.price.toFixed(2)}`:'sem preço'}}</small><span class="status-pill">{{s.active?'Ativo':'Inativo'}}</span></div></article></section></section>

<section v-else-if="view==='profissionais'" class="view-stack"><form v-if="showForm" class="panel operational-form" @submit.prevent="createProfessional"><h3>Novo profissional</h3><div class="form-grid"><input v-model="professionalForm.name" placeholder="Nome" required/><input v-model="professionalForm.email" type="email" placeholder="E-mail"/><input v-model="professionalForm.phone" placeholder="Telefone"/></div><button class="btn primary">Cadastrar</button></form><section class="entity-grid"><article v-for="p in professionals" :key="p.id" class="entity-card"><UserRoundCheck/><div><strong>{{p.name}}</strong><small>{{p.email||p.phone||'Sem contato'}}</small></div></article></section></section>

<section v-else-if="view==='landing'" class="view-stack"><section class="panel operational-form"><h3>Editor da landing page</h3><p>Conteúdo publicado no domínio do tenant.</p><input v-model="landingForm.title" placeholder="Título principal"/><input v-model="landingForm.subtitle" placeholder="Subtítulo"/><input v-model="landingForm.cta" placeholder="Texto do botão"/><div class="actions"><button class="btn" @click="saveLanding(false)">Salvar rascunho</button><button class="btn primary" @click="saveLanding(true)">Publicar</button></div></section><article class="landing-preview"><p class="eyebrow">Prévia</p><h2>{{landingForm.title}}</h2><p>{{landingForm.subtitle}}</p><button class="btn primary">{{landingForm.cta}}</button></article></section>

<section v-else-if="view==='whatsapp'" class="view-stack"><section class="integration-grid"><article class="panel"><p class="eyebrow">Evolution API</p><h3>WhatsApp do tenant</h3><pre class="status-box">{{JSON.stringify(whatsapp,null,2)}}</pre><button class="btn primary" @click="connectWhatsApp">Conectar / QR Code</button></article><form class="panel operational-form" @submit.prevent="sendMessage"><h3>Enviar mensagem</h3><input v-model="messageForm.to" placeholder="Número com DDD" required/><textarea v-model="messageForm.message" placeholder="Mensagem" required></textarea><button class="btn primary">Enviar</button></form></section></section>

<section v-else-if="view==='branding'" class="view-stack"><section class="panel operational-form"><h3>Marca e aplicativo</h3><div class="form-grid"><input v-model="brandingForm.public_name" placeholder="Nome público"/><input v-model="brandingForm.slogan" placeholder="Slogan"/><label>Cor principal<input v-model="brandingForm.primary_color" type="color"/></label><label>Cor de destaque<input v-model="brandingForm.accent_color" type="color"/></label><select v-model="brandingForm.theme_mode"><option value="system">Sistema</option><option value="light">Claro</option><option value="dark">Escuro</option></select></div><div class="actions"><button class="btn" @click="saveBranding(false)">Salvar</button><button class="btn primary" @click="saveBranding(true)">Publicar</button></div></section></section>

<section v-else-if="view==='dominios'" class="view-stack"><section class="panel"><h3>Domínio ativo</h3><div class="domain-card"><Globe2/><div><strong>{{tenantSettings?.hostname||manifest?.tenant.hostname||browserHostname}}</strong><small>Tenant {{tenantSettings?.slug||manifest?.tenant.slug}}</small></div><span class="status-pill">HTTPS</span></div><p>Domínios temporários e personalizados são provisionados pelo Control Plane; esta distribuição usa sempre o hostname resolvido do tenant.</p></section></section>

<section v-else-if="view==='builds'" class="view-stack"><section class="panel"><h3>Distribuições</h3><p>{{desktopInstructions()}}</p><div class="distribution-grid"><article><MonitorSmartphone/><strong>Desktop</strong><small>Windows • Linux • macOS</small><p>WebView remoto da versão web.</p></article><article><Smartphone/><strong>Mobile</strong><small>Android • iOS</small><p>Aplicativo dedicado conectado à API.</p></article><article><Download/><strong>PWA</strong><small>Instalável no navegador</small><p>Atualização centralizada.</p></article></div></section></section>

<section v-else class="view-stack"><section class="panel"><h3>Configurações do tenant</h3><div class="settings-list"><div><strong>Slug</strong><span>{{tenantSettings?.slug||'—'}}</span></div><div><strong>Hostname</strong><span>{{tenantSettings?.hostname||'—'}}</span></div><div><strong>Fuso</strong><span>{{tenantSettings?.timezone||'—'}}</span></div></div><form class="operational-form inline-form" @submit.prevent="saveSetting"><input v-model="settingForm.key" placeholder="Chave (ex.: booking_buffer_minutes)" required/><input v-model="settingForm.value" placeholder="Valor ou JSON" required/><button class="btn primary">Salvar configuração</button></form><pre class="status-box">{{JSON.stringify(tenantSettings?.preferences||{},null,2)}}</pre></section></section>
</main></div></div>
</template>
