#!/usr/bin/env sh
set -eu

DOMAIN="${ACME_DOMAIN:-scheduler.argws.com.br}"
EMAIL="${ACME_EMAIL:?ACME_EMAIL obrigatória}"
STAGING="${ACME_STAGING:-false}"
SERVER="letsencrypt"

if [ "$STAGING" = "true" ] || [ "$STAGING" = "1" ]; then
  SERVER="letsencrypt_test"
fi

mkdir -p /certs /acme.sh

acme.sh --set-default-ca --server "$SERVER"
acme.sh --register-account -m "$EMAIL" || true

# Issue both the base host and wildcard used by dynamic tenants.
# Example: scheduler.argws.com.br + *.scheduler.argws.com.br.
acme.sh --issue \
  --dns dns_cf \
  -d "$DOMAIN" \
  -d "*.$DOMAIN" \
  --keylength ec-256 \
  --server "$SERVER" \
  --renew-hook "date -Iseconds > /certs/last-renewed-at.txt" \
  || acme.sh --renew -d "$DOMAIN" --ecc --force --server "$SERVER"

acme.sh --install-cert -d "$DOMAIN" --ecc \
  --fullchain-file /certs/fullchain.pem \
  --key-file /certs/privkey.pem \
  --ca-file /certs/ca.pem \
  --cert-file /certs/cert.pem \
  --reloadcmd "date -Iseconds > /certs/last-installed-at.txt"

cat > /certs/README.txt <<EOF
Scheduler Pro ACME certificate bundle
Domain: $DOMAIN
Wildcard: *.$DOMAIN
Generated by acme.sh using Cloudflare DNS-01.

Files:
- fullchain.pem
- privkey.pem
- cert.pem
- ca.pem

Import these files in CloudPanel or mount them in the external TLS proxy.
EOF

# Keep the container alive and let acme.sh cron handle renewals.
crond -f
