import {
  addNode, createDocument, createNode, deepClone, duplicateNode, exportSubtree, getBreakpoints, getNode,
  importSubtree, moveNode, normalizeBreakpoints, normalizeDocument, parentOf, removeNode,
} from './model.js';
import { HistoryStack } from './history.js';
import { createProps, widgetDefinition, widgetGroups } from './registry.js';
import { baseRenderCss, exportStandaloneHtml, renderDocument } from './renderer.js';
import { conditionsToText, parseConditionsText } from './dynamic.js';
import { escapeHtml } from './sanitize.js';
import { MemoryAdapter } from './adapters.js';
import { BUILTIN_TEMPLATES } from './templates.js';
import { LocalComponentLibrary } from './library.js';
import { auditDocument } from './audit.js';
import { EDITOR_CSS } from './editor-styles.js';
import { can, createEditorPolicy } from './permissions.js';

function esc(value){return escapeHtml(value);}
function download(name, content, type='application/json'){
  const url=URL.createObjectURL(new Blob([content],{type})); const a=document.createElement('a'); a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
function toNumber(value){const n=Number(value);return Number.isFinite(n)?n:0;}
function safeJson(value,fallback){try{return JSON.parse(value);}catch{return fallback;}}
function variablesToText(value={}){return Object.entries(value||{}).map(([k,v])=>`${k} = ${v}`).join('\n');}
function variablesFromText(value){const result={};for(const line of String(value||'').split(/\r?\n/)){const i=line.indexOf('=');if(i<=0)continue;const key=line.slice(0,i).trim().replace(/[^a-zA-Z0-9_-]/g,'');if(key)result[key]=line.slice(i+1).trim();}return result;}

const HTMLElementBase = globalThis.HTMLElement || class {};
export class ArgwsVisualBuilder extends HTMLElementBase {
  constructor(){
    super(); this.attachShadow({mode:'open'});
    this._adapter=new MemoryAdapter(); this._document=createDocument(); this._history=new HistoryStack(120); this._history.reset(this._document);
    this._library=new LocalComponentLibrary(); this._selected=null; this._device='desktop'; this._styleState='base'; this._mobileDrawer=null;
    this._leftTab='elements'; this._rightTab='content'; this._dirty=false; this._loading=false; this._saving=false; this._publishing=false; this._search='';
    this._remoteTemplates=[]; this._remoteVersions=[]; this._autosaveTimer=null; this._canvasRaf=null; this._connected=false; this._context={editor:true}; this._clipboard=null; this._auditReport=null;
    this._policy=createEditorPolicy(); this._keyboard=this._onKeyboard.bind(this); this._beforeUnload=this._onBeforeUnload.bind(this);
  }
  set adapter(value){this._adapter=value||new MemoryAdapter();}
  get adapter(){return this._adapter;}
  set policy(value){this._policy=value||createEditorPolicy();if(this._connected)this._renderAll();}
  get policy(){return this._policy;}
  _allowed(capability){return can(this._policy,capability);}
  set context(value){this._context={editor:true,...(value||{})};if(this._connected)this._renderCanvas();}
  get context(){return this._context;}
  set document(value){this._document=normalizeDocument(value);this._history.reset(this._document);this._selected=this._document.builder.root_ids[0]||null;this._dirty=false;if(!getBreakpoints(this._document).some(bp=>bp.id===this._device))this._device='desktop';if(this._connected)this._renderAll();}
  get document(){return deepClone(this._document);}
  connectedCallback(){if(this._connected)return;this._connected=true;this._renderShell();this._bind();this._renderAll();globalThis.addEventListener?.('keydown',this._keyboard);globalThis.addEventListener?.('beforeunload',this._beforeUnload);if(this.hasAttribute('autoload'))void this.load();}
  disconnectedCallback(){globalThis.removeEventListener?.('keydown',this._keyboard);globalThis.removeEventListener?.('beforeunload',this._beforeUnload);if(this._autosaveTimer)clearTimeout(this._autosaveTimer);if(this._canvasRaf)cancelAnimationFrame(this._canvasRaf);}

  _renderShell(){
    this.shadowRoot.innerHTML=`<style>${EDITOR_CSS}</style><div class="shell">
      <header class="topbar">
        <div class="brand"><span class="brand-mark">A</span><span>ARGWS Visual Builder Pro</span></div>
        <button class="btn icon" data-action="page-settings" title="Configurações da página">⚙</button>
        <button class="btn icon" data-action="undo" title="Desfazer (Ctrl+Z)">↶</button><button class="btn icon" data-action="redo" title="Refazer (Ctrl+Y)">↷</button>
        <div id="device-actions" class="device-actions"></div>
        <button class="btn icon mobile-only" data-action="mobile-left" title="Elementos">＋</button><button class="btn icon mobile-only" data-action="mobile-right" title="Propriedades">⚙</button><div class="top-spacer"></div>
        <span id="save-status" style="font-size:11px;color:var(--muted)"></span>
        <button class="btn" data-action="audit">Auditar</button><button class="btn" data-action="import">Importar</button><button class="btn" data-action="export-json">JSON</button><button class="btn" data-action="export-html">HTML</button><button class="btn" data-action="preview">Preview</button>
        <button class="btn" data-action="save">Salvar</button><button class="btn primary" data-action="publish">Publicar</button><button class="btn icon danger" data-action="close" title="Fechar">×</button>
        <input id="import-file" type="file" accept="application/json,.json" hidden>
      </header>
      <div class="work">
        <aside class="panel left"><div class="tabs"><button class="tab" data-left="elements">Elementos</button><button class="tab" data-left="layers">Camadas</button><button class="tab" data-left="templates">Modelos</button><button class="tab" data-left="library">Biblioteca</button></div><div id="left-panel" class="panel-scroll"></div></aside>
        <main class="canvas-zone"><div class="canvas-toolbar"><span id="canvas-label"></span></div><div class="canvas-scroller"><div id="canvas-frame" class="canvas-frame"><div id="page-preview" class="page-preview"></div><div class="drop-root" data-drop-root></div></div></div></main>
        <aside class="panel right"><div id="inspector-head" class="inspector-head"></div><div class="tabs"><button class="tab" data-right="content">Conteúdo</button><button class="tab" data-right="style">Estilo</button><button class="tab" data-right="advanced">Avançado</button><button class="tab" data-right="history">Histórico</button></div><div id="right-panel" class="panel-scroll"></div></aside>
      </div><div class="mobile-backdrop" data-action="mobile-close"></div><div id="notice-host"></div></div>`;
  }
  _bind(){
    const root=this.shadowRoot; root.addEventListener('click',event=>this._onClick(event)); root.addEventListener('input',event=>this._onInput(event)); root.addEventListener('change',event=>this._onChange(event));
    root.addEventListener('dblclick',event=>this._onDoubleClick(event)); root.addEventListener('focusout',event=>this._onFocusOut(event)); root.addEventListener('dragstart',event=>this._onDragStart(event)); root.addEventListener('dragend',()=>this.shadowRoot.getElementById('canvas-frame').classList.remove('dragging'));
    root.addEventListener('dragover',event=>this._onDragOver(event)); root.addEventListener('drop',event=>this._onDrop(event)); root.getElementById('import-file').addEventListener('change',event=>void this._importFile(event));
  }

  async load(){
    this._loading=true;this._status('Carregando…');
    try{const doc=await this._adapter.load();this.document=doc;this._remoteTemplates=await Promise.resolve(this._adapter.listTemplates?.()).catch(()=>[])||[];this._notice('Página carregada.');}
    catch(error){this._notice(error?.message||'Falha ao carregar a página.','error');throw error;}
    finally{this._loading=false;this._status('');this._renderAll();}
  }
  async save({autosave=false}={}){
    if(!this._allowed('page.save'))throw new Error('Seu perfil não pode salvar páginas.');
    if(this._saving||!this._dirty)return null;this._saving=true;this._status(autosave?'Autosave…':'Salvando…');
    try{const fn=autosave&&this._adapter.autosave?this._adapter.autosave.bind(this._adapter):this._adapter.saveDraft.bind(this._adapter);const result=await fn(this.document);this._dirty=false;this._status('Salvo');if(!autosave)this._notice('Rascunho salvo.');this.dispatchEvent(new CustomEvent('upb-save',{detail:{document:this.document,result},bubbles:true,composed:true}));return result;}
    catch(error){this._status('Não salvo');this._notice(error?.message||'Falha ao salvar.','error');throw error;}
    finally{this._saving=false;this._renderToolbar();}
  }
  async publish(){
    if(!this._allowed('page.publish'))throw new Error('Seu perfil não pode publicar páginas.');
    if(this._publishing)return;this._publishing=true;this._status('Publicando…');
    try{if(this._dirty)await this.save();const result=await this._adapter.publish(this.document);this._status('Publicado');this._notice('Página publicada.');this.dispatchEvent(new CustomEvent('upb-publish',{detail:{document:this.document,result},bubbles:true,composed:true}));return result;}
    catch(error){this._status('Falha na publicação');this._notice(error?.message||'Falha ao publicar.','error');throw error;}
    finally{this._publishing=false;this._renderToolbar();}
  }

  _breakpoints(){return getBreakpoints(this._document);}
  _renderAll(){if(!this._connected)return;this._renderToolbar();this._renderLeft();this._renderCanvas();this._renderInspector();}
  _renderToolbar(){
    const root=this.shadowRoot,shell=root.querySelector('.shell');shell.classList.toggle('mobile-left',this._mobileDrawer==='left');shell.classList.toggle('mobile-right',this._mobileDrawer==='right');
    root.getElementById('device-actions').innerHTML=this._breakpoints().map(bp=>`<button class="btn ${bp.id===this._device?'active':''}" data-device="${esc(bp.id)}" title="${esc(bp.label)}">${bp.id==='desktop'?'▰':'▯'} ${esc(bp.label)}</button>`).join('');
    root.querySelector('[data-action=undo]').disabled=!this._history.canUndo()||!this._allowed('content.edit');root.querySelector('[data-action=redo]').disabled=!this._history.canRedo()||!this._allowed('content.edit');root.querySelector('[data-action=save]').disabled=this._saving||!this._dirty||!this._allowed('page.save');root.querySelector('[data-action=publish]').disabled=this._publishing||!this._allowed('page.publish');
    root.querySelector('[data-action=import]').disabled=!this._allowed('page.import');root.querySelector('[data-action=export-json]').disabled=!this._allowed('page.export');root.querySelector('[data-action=export-html]').disabled=!this._allowed('page.export');
    const bp=this._breakpoints().find(row=>row.id===this._device)||this._breakpoints()[0];const frame=root.getElementById('canvas-frame');frame.style.width=`${bp.canvas||1180}px`;root.getElementById('canvas-label').textContent=`${bp.label} · ${bp.canvas||1180}px · cascata responsiva`;
    for(const el of root.querySelectorAll('[data-left]'))el.classList.toggle('active',el.dataset.left===this._leftTab);for(const el of root.querySelectorAll('[data-right]'))el.classList.toggle('active',el.dataset.right===this._rightTab);
  }
  _renderLeft(){
    const host=this.shadowRoot.getElementById('left-panel');
    if(this._leftTab==='elements'){
      if(!this._allowed('element.add')){host.innerHTML='<div class="responsive-note">Seu perfil permite editar conteúdo existente, mas não adicionar elementos.</div>';return;}
      const groups=widgetGroups();let html=`<input class="search" data-role="widget-search" value="${esc(this._search)}" placeholder="Buscar elemento…">`;
      for(const [group,widgets] of Object.entries(groups)){const filtered=widgets.filter(w=>`${w.label} ${w.type}`.toLowerCase().includes(this._search.toLowerCase()));if(!filtered.length)continue;html+=`<div class="group-title">${esc(group)}</div><div class="widget-grid">${filtered.map(w=>`<div class="widget" draggable="true" data-widget-type="${esc(w.type)}"><span class="widget-icon">${esc(w.icon)}</span><span>${esc(w.label)}</span></div>`).join('')}</div>`;}
      host.innerHTML=html;return;
    }
    if(this._leftTab==='layers'){host.innerHTML=this._document.builder.root_ids.length?this._document.builder.root_ids.map(id=>this._layerHtml(id)).join(''):'<div class="responsive-note">A página ainda não possui elementos.</div>';return;}
    if(this._leftTab==='library'){
      const items=this._library.list();host.innerHTML=`<div class="responsive-note">Salve containers, seções ou widgets e reutilize em qualquer página deste navegador.</div><div class="group-title">Meus componentes</div>${items.length?items.map(item=>`<div class="template-card"><strong>${esc(item.name)}</strong><p>${esc(item.category||'Componente')} · ${esc(new Date(item.created_at).toLocaleString('pt-BR'))}</p><div class="template-actions"><button class="btn" data-library-insert="${esc(item.id)}">Inserir</button><button class="btn danger" data-library-delete="${esc(item.id)}">Excluir</button></div></div>`).join(''):'<div class="responsive-note">Sua biblioteca está vazia.</div>'}`;return;
    }
    let html='<div class="group-title">Modelos incluídos</div>';html+=BUILTIN_TEMPLATES.map(t=>`<div class="template-card"><strong>${esc(t.name)}</strong><p>${esc(t.description)}</p><button class="btn" data-template-local="${esc(t.key)}">Aplicar modelo</button></div>`).join('');
    if(this._remoteTemplates.length){html+='<div class="group-title">Modelos do projeto</div>'+this._remoteTemplates.map(t=>`<div class="template-card"><strong>${esc(t.name||t.key)}</strong><p>${esc(t.description||'Modelo disponível no backend.')}</p><button class="btn" data-template-remote="${esc(t.key)}">Aplicar</button></div>`).join('');}host.innerHTML=html;
  }
  _layerHtml(id){const node=getNode(this._document,id);if(!node)return'';const def=widgetDefinition(node.type);return `<div class="layer ${this._selected===id?'active':''}" data-select-node="${esc(id)}"><span>${esc(def.icon)}</span><span>${esc(def.label)}</span><span class="layer-actions"><button class="mini" data-node-up="${esc(id)}" title="Subir">↑</button><button class="mini" data-node-down="${esc(id)}" title="Descer">↓</button></span></div>${node.children.length?`<div class="tree-indent">${node.children.map(child=>this._layerHtml(child)).join('')}</div>`:''}`;}
  _scheduleCanvasRender(){if(this._canvasRaf)cancelAnimationFrame(this._canvasRaf);this._canvasRaf=requestAnimationFrame(()=>{this._canvasRaf=null;this._renderCanvas();});}
  _renderCanvas(){
    const preview=this.shadowRoot.getElementById('page-preview'),rendered=renderDocument(this._document,{device:this._device,context:{...this._context,editor:true},responsive:false});preview.innerHTML=`<style>${rendered.css}</style>${rendered.html}`;
    if(!this._document.builder.root_ids.length)preview.innerHTML=`<style>${baseRenderCss(this._document.global_styles,this._document.settings,this._document.design_system)}</style><div class="empty-canvas"><div><strong>Página vazia</strong>Arraste um elemento da esquerda, toque em um widget ou aplique um modelo.</div></div>`;
    for(const el of preview.querySelectorAll('[data-upb-node]')){const id=el.getAttribute('data-upb-node');el.setAttribute('draggable','true');if(id===this._selected)el.classList.add('selected');const badge=document.createElement('span');badge.className='node-badge';badge.textContent=widgetDefinition(getNode(this._document,id)?.type||'').label;el.prepend(badge);}
    this.dispatchEvent(new CustomEvent('upb-preview-rendered',{detail:{root:preview,document:this.document,device:this._device},bubbles:true,composed:true}));
  }
  _renderInspector(){
    const head=this.shadowRoot.getElementById('inspector-head'),host=this.shadowRoot.getElementById('right-panel'),node=this._selected?getNode(this._document,this._selected):null;
    if(!node){head.innerHTML='<div class="inspector-title">Configurações da página</div><div class="inspector-sub">Site settings · design system · SEO</div>';host.innerHTML=this._pageSettingsHtml();return;}
    const def=widgetDefinition(node.type);head.innerHTML=`<div class="inspector-title">${esc(def.label)}</div><div class="inspector-sub">${esc(node.type)} · ${esc(node.id)}</div>`;
    if(this._rightTab==='content'){host.innerHTML=this._contentInspector(node,def);return;}if(this._rightTab==='style'){host.innerHTML=this._styleInspector(node);return;}if(this._rightTab==='advanced'){host.innerHTML=this._advancedInspector(node);return;}host.innerHTML=this._historyInspector();
  }
  _fieldHtml(node,field){
    let value=node.props[field.key]??field.default??'';if(field.key==='images_text'&&!value&&Array.isArray(node.props.images))value=node.props.images.join('\n');if(field.key==='items_text'&&!value&&Array.isArray(node.props.items))value=node.props.items.map(item=>`${item.question||item.name||item.title||item.label||''} | ${item.answer||item.text||item.url||''}`).join('\n');
    let input='';if(field.control==='textarea')input=`<textarea data-prop="${esc(field.key)}">${esc(Array.isArray(value)?JSON.stringify(value):value)}</textarea>`;else if(field.control==='select')input=`<select data-prop="${esc(field.key)}">${field.options.map(([v,l])=>`<option value="${esc(v)}" ${String(value)===String(v)?'selected':''}>${esc(l)}</option>`).join('')}</select>`;else if(field.control==='toggle')return `<label class="check"><input type="checkbox" data-prop="${esc(field.key)}" ${value?'checked':''}> ${esc(field.label)}</label>${this._bindingHtml(node,field)}`;else input=`<input type="${field.control==='number'?'number':'text'}" data-prop="${esc(field.key)}" value="${esc(value)}" ${field.min!=null?`min="${field.min}"`:''} ${field.max!=null?`max="${field.max}"`:''}>`;
    return `<div class="field"><label>${esc(field.label)}</label>${input}</div>${this._bindingHtml(node,field)}`;
  }
  _bindingHtml(node,field){if(['images_text','items_text','fields_text','actions_text','features_text'].includes(field.key)||field.control==='toggle')return'';const value=typeof node.bindings?.[field.key]==='string'?node.bindings[field.key]:node.bindings?.[field.key]?.path||'';return `<div class="binding"><span>ƒx</span><input data-binding="${esc(field.key)}" value="${esc(value)}" placeholder="Ex.: tenant.name ou item.title"></div>`;}
  _contentInspector(node,def){let html='<div class="section"><h4>Conteúdo</h4>';for(const field of def.fields||[])html+=this._fieldHtml(node,field);if(['image','logo','hero'].includes(node.type)&&this._adapter.upload)html+=`<div class="field"><label>Upload para o storage</label><input type="file" accept="image/*" data-upload-image></div>`;if(def.acceptsChildren)html+=`<div class="responsive-note">Aceita elementos filhos. Arraste sobre ele ou selecione-o e toque em um widget.</div>`;return html+'</div>';}
  _styleTarget(node,state=this._styleState,device=this._device){
    if(state==='base')return device==='desktop'?node.style:(node.responsive[device]||={});
    if(device==='desktop')return(node.states[state]||={});
    node.responsive_states[device]||={hover:{},focus:{},active:{}};return(node.responsive_states[device][state]||={});
  }
  _effectiveStyle(node,key){
    const state=this._styleState;if(state!=='base'){const bps=this._breakpoints(),idx=Math.max(0,bps.findIndex(bp=>bp.id===this._device));let value=node.states?.[state]?.[key];for(const bp of bps.slice(1,idx+1))if(node.responsive_states?.[bp.id]?.[state]?.[key]!=null)value=node.responsive_states[bp.id][state][key];return value??'';}
    const bps=this._breakpoints(),idx=Math.max(0,bps.findIndex(bp=>bp.id===this._device));let value=node.style?.[key];for(const bp of bps.slice(1,idx+1))if(node.responsive?.[bp.id]?.[key]!=null)value=node.responsive[bp.id][key];return value??'';
  }
  _styleInspector(node){
    const num=(key,label,min=-500,max=3000)=>`<div class="field"><label>${label}</label><input type="number" data-style="${key}" value="${esc(this._effectiveStyle(node,key))}" min="${min}" max="${max}"></div>`;const txt=(key,label)=>`<div class="field"><label>${label}</label><input type="text" data-style="${key}" value="${esc(this._effectiveStyle(node,key))}"></div>`;const sel=(key,label,options)=>`<div class="field"><label>${label}</label><select data-style="${key}"><option value="">Herdar / padrão</option>${options.map(([v,l])=>`<option value="${v}" ${String(this._effectiveStyle(node,key))===v?'selected':''}>${l}</option>`).join('')}</select></div>`;
    return `<div class="section"><h4>${esc(this._breakpoints().find(bp=>bp.id===this._device)?.label||this._device)} · Estilos</h4><div class="state-switch">${['base','hover','focus','active'].map(state=>`<button class="btn ${this._styleState===state?'active':''}" data-style-state="${state}">${state==='base'?'Normal':state}</button>`).join('')}</div><div class="responsive-note">Todos os controles podem variar por breakpoint. Estados Hover/Focus/Active também são responsivos.</div></div>
      <div class="section"><h4>Cores e tipografia</h4><div class="field"><label>Cor do texto</label><div class="color-row"><input type="color" data-style-color="color" value="${this._colorValue(this._effectiveStyle(node,'color'),'#1d273a')}"><input data-style="color" value="${esc(this._effectiveStyle(node,'color'))}" placeholder="#1d273a"></div></div><div class="field"><label>Fundo</label><div class="color-row"><input type="color" data-style-color="backgroundColor" value="${this._colorValue(this._effectiveStyle(node,'backgroundColor'),'#ffffff')}"><input data-style="backgroundColor" value="${esc(this._effectiveStyle(node,'backgroundColor'))}" placeholder="#ffffff"></div></div><div class="field-row">${num('fontSize','Fonte',8,180)}${num('fontWeight','Peso',100,1000)}</div><div class="field-row">${num('lineHeight','Altura linha',0,5)}${num('letterSpacing','Espaçamento',-20,100)}</div>${sel('textAlign','Alinhamento',[['left','Esquerda'],['center','Centro'],['right','Direita'],['justify','Justificado']])}</div>
      <div class="section"><h4>Layout</h4><div class="field-row">${num('padding','Padding',0,400)}${num('margin','Margem',-400,400)}</div><div class="field-row">${num('gap','Gap',0,240)}${num('borderRadius','Raio',0,300)}</div>${txt('width','Largura')}${txt('maxWidth','Largura máxima')}${txt('minHeight','Altura mínima')}${sel('display','Display',[['block','Block'],['flex','Flex'],['grid','Grid'],['inline-flex','Inline flex'],['none','Oculto']])}${sel('flexDirection','Direção Flex',[['row','Horizontal'],['column','Vertical'],['row-reverse','Horizontal reverso'],['column-reverse','Vertical reverso']])}${sel('justifyContent','Distribuição',[['flex-start','Início'],['center','Centro'],['flex-end','Fim'],['space-between','Entre'],['space-around','Ao redor'],['space-evenly','Uniforme']])}${sel('alignItems','Alinhamento cruzado',[['stretch','Esticar'],['flex-start','Início'],['center','Centro'],['flex-end','Fim']])}</div>
      <div class="section"><h4>Borda, sombra e transformação</h4>${txt('border','Borda CSS')}${txt('boxShadow','Sombra CSS')}${txt('transform','Transform CSS')}${txt('filter','Filtro CSS')}${num('opacity','Opacidade',0,1)}</div>`;
  }
  _advancedInspector(node){const hidden=node.responsive.hidden||{},m=node.motion||{},conditions=conditionsToText(node.conditions);return `<div class="section"><h4>Visibilidade responsiva</h4><div class="responsive-switch">${this._breakpoints().map(bp=>`<label class="check"><input type="checkbox" data-hidden="${esc(bp.id)}" ${hidden[bp.id]?'checked':''}> ocultar em ${esc(bp.label)}</label>`).join('')}</div></div>
      <div class="section"><h4>Motion Effects</h4><div class="field"><label>Animação de entrada</label><select data-motion="entrance"><option value="">Nenhuma</option>${[['fade','Fade'],['slide-up','Slide up'],['slide-left','Slide left'],['zoom','Zoom']].map(([v,l])=>`<option value="${v}" ${m.entrance===v?'selected':''}>${l}</option>`).join('')}</select></div><div class="field-row"><div class="field"><label>Duração ms</label><input type="number" data-motion-number="duration" value="${esc(m.duration||600)}"></div><div class="field"><label>Atraso ms</label><input type="number" data-motion-number="delay" value="${esc(m.delay||0)}"></div></div><label class="check"><input type="checkbox" data-motion-toggle="sticky" ${m.sticky?'checked':''}> Sticky</label><div class="field"><label>Offset sticky</label><input type="number" data-motion-number="sticky_offset" value="${esc(m.sticky_offset||0)}"></div></div>
      <div class="section"><h4>Condições de exibição</h4><div class="field"><label>Uma regra por linha: caminho | operador | valor</label><textarea class="code" data-conditions>${esc(conditions)}</textarea></div><div class="hint">Operadores: eq, neq, gt, gte, lt, lte, contains, in, exists, empty, truthy, falsy.</div></div>
      <div class="section"><h4>CSS e metadados</h4><div class="field"><label>Classes globais</label><input data-meta="classes" value="${esc(Array.isArray(node.meta?.classes)?node.meta.classes.join(' '):node.meta?.classes||'')}" placeholder="card destaque"></div><div class="field"><label>Âncora</label><input data-meta="anchor" value="${esc(node.meta?.anchor||'')}"></div><div class="field"><label>Atributos seguros JSON</label><textarea class="code" data-attributes>${esc(JSON.stringify(node.meta?.attributes||{},null,2))}</textarea></div><div class="field"><label>Declarações CSS adicionais</label><textarea class="code" data-meta="customStyle" placeholder="aspect-ratio:16/9; overflow:hidden">${esc(node.meta?.customStyle||'')}</textarea></div></div>
      <div class="section"><h4>Interactions</h4><div class="field"><label>Eventos e ações JSON</label><textarea class="code" data-interactions>${esc(JSON.stringify(node.interactions||[],null,2))}</textarea></div><div class="hint">Ex.: [{"event":"click","actions":[{"type":"open_popup","target":"lead"}]}]</div></div>
      <div class="section"><h4>Ações</h4><div class="template-actions"><button class="btn" data-node-library="${esc(node.id)}">Salvar componente</button><button class="btn" data-node-duplicate="${esc(node.id)}">Duplicar</button><button class="btn danger" data-node-delete="${esc(node.id)}">Excluir</button></div></div>`;}
  _historyInspector(){
    const local=`<div class="section"><h4>Histórico local</h4><div class="responsive-note">${this._history.past.length} estado(s) para desfazer · ${this._history.future.length} para refazer.</div><div class="template-actions" style="margin-top:8px"><button class="btn" data-action="undo" ${this._history.canUndo()?'':'disabled'}>Desfazer</button><button class="btn" data-action="redo" ${this._history.canRedo()?'':'disabled'}>Refazer</button></div></div>`;
    const remote=this._adapter.versions?`<div class="section"><h4>Revisões do servidor</h4><button class="btn" data-action="refresh-versions">Atualizar</button><div style="margin-top:8px">${this._remoteVersions.length?this._remoteVersions.map(v=>`<div class="history-item"><strong>Versão ${esc(v.version_number??v.id)}</strong><span>${esc(v.label||v.created_at||'')}</span><button class="btn" data-version-restore="${esc(v.id)}">Restaurar</button></div>`).join(''):'<div class="responsive-note">Nenhuma revisão carregada.</div>'}</div></div>`:'';return local+remote;
  }
  _pageSettingsHtml(){
    const g=this._document.global_styles||{},seo=this._document.seo||{},settings=this._document.settings||{},ds=this._document.design_system||{},project=this._document.project||{};const color=(key,label,fallback)=>`<div class="field"><label>${label}</label><div class="color-row"><input type="color" data-global-color="${key}" value="${this._colorValue(g[key],fallback)}"><input data-global="${key}" value="${esc(g[key]||fallback)}"></div></div>`;
    const breakpoints=this._breakpoints().map(bp=>`<div class="breakpoint"><input data-breakpoint-label="${esc(bp.id)}" value="${esc(bp.label)}"><input type="number" data-breakpoint-max="${esc(bp.id)}" value="${bp.max??''}" placeholder="max"><input type="number" data-breakpoint-canvas="${esc(bp.id)}" value="${esc(bp.canvas)}" placeholder="canvas"><button class="mini" data-breakpoint-delete="${esc(bp.id)}" ${['desktop','tablet','mobile'].includes(bp.id)?'disabled':''}>×</button></div>`).join('');
    const audit=this._auditReport?`<div class="section"><h4>Auditoria</h4><div class="audit-score">${this._auditReport.score}/100</div>${this._auditReport.issues.slice(0,15).map(i=>`<div class="audit-item ${esc(i.severity)}">${esc(i.message)}${i.node_id?` · ${esc(i.node_id)}`:''}</div>`).join('')}</div>`:'';
    return `<div class="page-settings"><div class="section"><h4>Documento</h4><div class="field"><label>Título interno</label><input data-document-title value="${esc(this._document.title||'')}"></div><div class="field"><label>Superfície</label><select data-document-surface>${['PAGE','HEADER','FOOTER','POPUP','SINGLE','ARCHIVE'].map(v=>`<option value="${v}" ${this._document.surface===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>Largura do conteúdo</label><input type="number" data-setting="content_width" value="${esc(settings.content_width||1180)}"></div></div>
      <div class="section"><h4>Identidade visual</h4>${color('primary','Primária','#3151cf')}${color('secondary','Secundária','#151c31')}${color('accent','Destaque','#6d72ef')}${color('background','Fundo','#ffffff')}${color('text','Texto','#1d273a')}<div class="field"><label>Fonte de títulos</label><input data-global="heading_font" value="${esc(g.heading_font||'Inter')}"></div><div class="field"><label>Fonte do corpo</label><input data-global="body_font" value="${esc(g.body_font||'Inter')}"></div><div class="field-row"><div class="field"><label>Raio global</label><input type="number" min="0" max="100" data-global="radius" value="${esc(g.radius||16)}"></div><div class="field"><label>Raio de botão</label><input type="number" min="0" max="100" data-global="button_radius" value="${esc(g.button_radius||12)}"></div></div></div>
      <div class="section"><h4>Breakpoints</h4><div class="hint">Nome · largura máxima · largura do canvas. Desktop é a base.</div><div style="margin-top:8px">${breakpoints}</div><button class="btn" data-action="add-breakpoint">Adicionar breakpoint</button></div>
      <div class="section"><h4>Variáveis / Design tokens</h4><div class="field"><textarea class="code" data-design-variables placeholder="space-md = 16px">${esc(variablesToText(ds.variables||{}))}</textarea></div></div>
      <div class="section"><h4>Class Manager</h4><div class="field"><label>Classes globais em JSON</label><textarea class="code" data-design-classes>${esc(JSON.stringify(ds.classes||{},null,2))}</textarea></div><div class="hint">Ex.: {"card":{"style":{"borderRadius":24},"states":{"hover":{"transform":"translateY(-4px)"}}}}</div></div>
      <div class="section"><h4>CSS global</h4><div class="field"><textarea class="code" data-setting="custom_css" placeholder=".upb-page .minha-classe { ... }">${esc(settings.custom_css||'')}</textarea></div></div>
      <div class="section"><h4>SEO</h4><div class="field"><label>Título</label><input data-seo="title" value="${esc(seo.title||'')}"></div><div class="field"><label>Descrição</label><textarea data-seo="description">${esc(seo.description||'')}</textarea></div><div class="field"><label>Imagem de compartilhamento</label><input data-seo="share_image" value="${esc(seo.share_image||'')}"></div><div class="field"><label>Canonical</label><input data-seo="canonical" value="${esc(seo.canonical||'')}"></div><div class="field"><label>Robots</label><input data-seo="robots" value="${esc(seo.robots||'index,follow')}"></div><div class="field"><label>Open Graph JSON</label><textarea class="code" data-seo-json="open_graph">${esc(JSON.stringify(seo.open_graph||{},null,2))}</textarea></div><div class="field"><label>Twitter JSON</label><textarea class="code" data-seo-json="twitter">${esc(JSON.stringify(seo.twitter||{},null,2))}</textarea></div><div class="field"><label>JSON-LD (lista JSON)</label><textarea class="code" data-seo-json="structured_data">${esc(JSON.stringify(seo.structured_data||[],null,2))}</textarea></div><button class="btn" data-action="audit">Executar auditoria</button></div>
      <div class="section"><h4>Ativos globais</h4><div class="field"><label>Fontes / ícones / mídia em JSON</label><textarea class="code" data-project-json="assets">${esc(JSON.stringify(project.assets||{fonts:[],icons:[],media:[]},null,2))}</textarea></div><div class="hint">Fontes customizadas podem ser registradas com family, url, weight, style e format.</div></div>
      <div class="section"><h4>Internacionalização</h4><div class="field"><label>Configuração i18n JSON</label><textarea class="code" data-project-json="i18n">${esc(JSON.stringify(project.i18n||{},null,2))}</textarea></div></div>
      <div class="section"><h4>Data Sources</h4><div class="field"><label>Requisitos globais JSON</label><textarea class="code" data-project-json="data_requirements">${esc(JSON.stringify(project.data_requirements||[],null,2))}</textarea></div><div class="hint">Os handlers reais são registrados no host. O documento guarda somente descritores de consulta.</div></div>
      <div class="section"><h4>Custom Code</h4><div class="field"><label>Snippets JSON</label><textarea class="code" data-project-json="custom_code">${esc(JSON.stringify(project.custom_code||[],null,2))}</textarea></div><div class="hint">JavaScript só é emitido no standalone quando marcado trusted e explicitamente permitido pelo host.</div></div>
      <div class="section"><h4>Permissões do projeto</h4><div class="field"><label>Roles JSON</label><textarea class="code" data-project-json="permissions">${esc(JSON.stringify(project.permissions||{roles:{}},null,2))}</textarea></div></div>${audit}</div>`;
  }
  _colorValue(value,fallback){const raw=String(value||'');return /^#[0-9a-f]{6}$/i.test(raw)?raw:fallback;}

  _onClick(event){
    const t=event.target.closest?.('button,[data-select-node],[data-upb-node],[data-widget-type],[data-action],[data-style-state]');if(!t)return;
    if(t.dataset.widgetType){this._insertWidget(t.dataset.widgetType);return;}if(t.dataset.device){this._device=t.dataset.device;this._renderAll();return;}if(t.dataset.left){this._leftTab=t.dataset.left;this._renderAll();return;}if(t.dataset.right){this._rightTab=t.dataset.right;if(this._rightTab==='history')void this._loadVersions();this._renderAll();return;}if(t.dataset.styleState){this._styleState=t.dataset.styleState;this._renderInspector();return;}
    if(t.dataset.selectNode){this._selected=t.dataset.selectNode;if(innerWidth<=780)this._mobileDrawer='right';this._renderAll();return;}if(t.matches('[data-upb-node]')||t.closest('[data-upb-node]')){const nodeEl=t.matches('[data-upb-node]')?t:t.closest('[data-upb-node]');this._selected=nodeEl.dataset.upbNode;if(innerWidth<=780)this._mobileDrawer='right';this._renderAll();return;}
    const a=t.dataset.action;if(a){if(a==='undo')this._undo();else if(a==='redo')this._redo();else if(a==='save')void this.save();else if(a==='publish')void this.publish();else if(a==='page-settings'){this._selected=null;this._mobileDrawer=innerWidth<=780?'right':this._mobileDrawer;this._renderAll();}else if(a==='import')this.shadowRoot.getElementById('import-file').click();else if(a==='export-json')download(`${this._slugName()}.json`,JSON.stringify(this.document,null,2));else if(a==='export-html')download(`${this._slugName()}.html`,exportStandaloneHtml(this.document),'text/html');else if(a==='preview')this._previewWindow();else if(a==='audit'){this._auditReport=auditDocument(this.document);this._selected=null;this._mobileDrawer=innerWidth<=780?'right':this._mobileDrawer;this._renderInspector();}else if(a==='mobile-left'){this._mobileDrawer=this._mobileDrawer==='left'?null:'left';this._renderToolbar();}else if(a==='mobile-right'){this._mobileDrawer=this._mobileDrawer==='right'?null:'right';this._renderToolbar();}else if(a==='mobile-close'){this._mobileDrawer=null;this._renderToolbar();}else if(a==='add-breakpoint')this._addBreakpoint();else if(a==='refresh-versions')void this._loadVersions(true);else if(a==='close')this.dispatchEvent(new CustomEvent('upb-close',{bubbles:true,composed:true}));return;}
    if(t.dataset.templateLocal){if(!this._allowed('template.apply'))return;const tpl=BUILTIN_TEMPLATES.find(x=>x.key===t.dataset.templateLocal);if(tpl)this._replaceDocument(tpl.create(),'Modelo aplicado.');return;}if(t.dataset.templateRemote){void this._applyRemoteTemplate(t.dataset.templateRemote);return;}
    if(t.dataset.nodeDuplicate){if(!this._allowed('element.add'))return;const copy=duplicateNode(this._document,t.dataset.nodeDuplicate);if(copy){this._selected=copy.id;this._mutated({checkpoint:true});}return;}if(t.dataset.nodeDelete){this._deleteNode(t.dataset.nodeDelete);return;}if(t.dataset.nodeLibrary){this._saveToLibrary(t.dataset.nodeLibrary);return;}if(t.dataset.nodeUp){this._moveSibling(t.dataset.nodeUp,-1);return;}if(t.dataset.nodeDown){this._moveSibling(t.dataset.nodeDown,1);return;}
    if(t.dataset.libraryInsert){this._insertLibrary(t.dataset.libraryInsert);return;}if(t.dataset.libraryDelete){if(!this._allowed('library.manage'))return;this._library.remove(t.dataset.libraryDelete);this._renderLeft();return;}if(t.dataset.versionRestore){void this._restoreVersion(t.dataset.versionRestore);return;}if(t.dataset.breakpointDelete){this._deleteBreakpoint(t.dataset.breakpointDelete);}
  }
  _insertWidget(type){if(!this._allowed('element.add')){this._notice('Seu perfil não pode adicionar elementos.','error');return;}let parentId=null;if(this._selected){const selected=getNode(this._document,this._selected);if(widgetDefinition(selected?.type).acceptsChildren)parentId=selected.id;}const n=createNode(type,createProps(type));addNode(this._document,n,parentId);this._selected=n.id;if(innerWidth<=780)this._mobileDrawer='right';this._mutated({checkpoint:true});}
  _onInput(event){const el=event.target;if(el.dataset.role==='widget-search'){this._search=el.value;this._renderLeft();return;}this._applyField(el,false);}
  _onChange(event){const el=event.target;if(el.matches('[data-upload-image]')){void this._uploadImage(el);return;}this._applyField(el,true);}
  _applyField(el,commit){
    const node=this._selected?getNode(this._document,this._selected):null;let changed=false;
    if(node&&el.dataset.prop&&!this._allowed('content.edit'))return;
    if(node&&(el.dataset.style||el.dataset.styleColor)&&!this._allowed('style.edit'))return;
    if(node&&(el.dataset.hidden||el.dataset.meta||el.matches?.('[data-conditions]')||el.matches?.('[data-interactions]')||el.matches?.('[data-attributes]')||el.dataset.motion||el.dataset.motionNumber||el.dataset.motionToggle)&&!this._allowed('advanced.edit'))return;
    if((el.dataset.global||el.dataset.globalColor||el.matches?.('[data-design-variables]')||el.matches?.('[data-design-classes]'))&&!this._allowed('design_system.edit'))return;
    if(el.dataset.seo&&!this._allowed('seo.edit'))return;
    if(el.dataset.projectJson==='custom_code'&&!this._allowed('custom_code.edit'))return;
    if(el.dataset.projectJson==='data_requirements'&&!this._allowed('data_source.configure'))return;
    if(el.dataset.projectJson==='assets'&&!this._allowed('asset.upload')&&!this._allowed('design_system.edit'))return;
    if(el.dataset.projectJson==='permissions'&&!this._allowed('design_system.edit'))return;
    if(el.dataset.projectJson==='i18n'&&!this._allowed('content.edit')&&!this._allowed('design_system.edit'))return;
    if(node&&el.dataset.prop){const def=widgetDefinition(node.type).fields?.find(f=>f.key===el.dataset.prop);node.props[el.dataset.prop]=el.type==='checkbox'?el.checked:def?.control==='number'?toNumber(el.value):el.value;changed=true;}
    if(node&&el.dataset.binding){node.bindings=node.bindings||{};if(el.value.trim())node.bindings[el.dataset.binding]=el.value.trim();else delete node.bindings[el.dataset.binding];changed=true;}
    if(node&&el.dataset.style){const target=this._styleTarget(node);if(el.value==='')delete target[el.dataset.style];else target[el.dataset.style]=['fontSize','fontWeight','borderRadius','padding','margin','gap','minHeight','opacity','lineHeight','letterSpacing'].includes(el.dataset.style)?toNumber(el.value):el.value;changed=true;}
    if(node&&el.dataset.styleColor){const target=this._styleTarget(node),key=el.dataset.styleColor;target[key]=el.value;changed=true;this._syncSiblingInput(el,`[data-style="${key}"]`);}
    if(node&&el.dataset.hidden){node.responsive.hidden[el.dataset.hidden]=el.checked;changed=true;}if(node&&el.dataset.meta){node.meta=node.meta||{};node.meta[el.dataset.meta]=el.dataset.meta==='classes'?el.value.split(/[\s,]+/).filter(Boolean):el.value;changed=true;}
    if(node&&el.matches('[data-conditions]')){node.conditions=parseConditionsText(el.value);changed=true;}if(node&&el.matches('[data-interactions]')&&commit){const parsed=safeJson(el.value,null);if(Array.isArray(parsed)){node.interactions=parsed;changed=true;}else{this._notice('JSON de Interactions inválido.','error');return;}}if(node&&el.matches('[data-attributes]')&&commit){const parsed=safeJson(el.value,null);if(parsed&&typeof parsed==='object'&&!Array.isArray(parsed)){node.meta.attributes=parsed;changed=true;}else{this._notice('JSON de atributos inválido.','error');return;}}if(node&&el.dataset.motion){node.motion[el.dataset.motion]=el.value;changed=true;}if(node&&el.dataset.motionNumber){node.motion[el.dataset.motionNumber]=toNumber(el.value);changed=true;}if(node&&el.dataset.motionToggle){node.motion[el.dataset.motionToggle]=el.checked;changed=true;}
    if(el.dataset.global){this._document.global_styles[el.dataset.global]=el.type==='number'?toNumber(el.value):el.value;changed=true;}if(el.dataset.globalColor){this._document.global_styles[el.dataset.globalColor]=el.value;changed=true;this._syncSiblingInput(el,`[data-global="${el.dataset.globalColor}"]`);}if(el.dataset.seo){this._document.seo[el.dataset.seo]=el.value;changed=true;}if(el.dataset.seoJson&&commit){const parsed=safeJson(el.value,null);if(parsed!==null){this._document.seo[el.dataset.seoJson]=parsed;changed=true;}else{this._notice('JSON de SEO inválido.','error');return;}}if(el.dataset.projectJson&&commit){const parsed=safeJson(el.value,null);if(parsed!==null){this._document.project ||= {};this._document.project[el.dataset.projectJson]=parsed;changed=true;}else{this._notice('JSON de configuração do projeto inválido.','error');return;}}if(el.dataset.setting){this._document.settings[el.dataset.setting]=el.type==='number'?toNumber(el.value):el.value;changed=true;}
    if(el.matches('[data-document-title]')){this._document.title=el.value;changed=true;}if(el.matches('[data-document-surface]')){this._document.surface=el.value;changed=true;}if(el.matches('[data-design-variables]')){this._document.design_system.variables=variablesFromText(el.value);changed=true;}if(el.matches('[data-design-classes]')&&commit){const parsed=safeJson(el.value,null);if(parsed&&typeof parsed==='object'){this._document.design_system.classes=parsed;changed=true;}else{this._notice('JSON de classes inválido.','error');return;}}
    const bpId=el.dataset.breakpointLabel||el.dataset.breakpointMax||el.dataset.breakpointCanvas;if(bpId){const bp=this._document.design_system.breakpoints.find(row=>row.id===bpId);if(bp){if(el.dataset.breakpointLabel)bp.label=el.value;if(el.dataset.breakpointMax)bp.max=el.value===''?null:Math.max(240,toNumber(el.value));if(el.dataset.breakpointCanvas)bp.canvas=Math.max(240,toNumber(el.value));this._document.design_system.breakpoints=normalizeBreakpoints(this._document.design_system.breakpoints);changed=true;}}
    if(changed)this._mutated({checkpoint:commit,renderInspector:commit,renderLeft:false});
  }
  _syncSiblingInput(el,selector){const parent=el.parentElement;const other=parent?.querySelector(selector);if(other)other.value=el.value;}
  _onDoubleClick(event){if(!this._allowed('content.edit'))return;const target=event.target.closest?.('[data-upb-inline-prop]');if(!target)return;event.preventDefault();target.setAttribute('contenteditable','true');target.focus();const range=document.createRange();range.selectNodeContents(target);const selection=globalThis.getSelection?.();selection?.removeAllRanges();selection?.addRange(range);}
  _onFocusOut(event){const target=event.target;if(!target?.matches?.('[contenteditable=true][data-upb-inline-prop]'))return;const nodeEl=target.closest('[data-upb-node]'),node=nodeEl?getNode(this._document,nodeEl.dataset.upbNode):null;if(node){node.props[target.dataset.upbInlineProp]=target.textContent||'';this._selected=node.id;this._mutated({checkpoint:true});}target.removeAttribute('contenteditable');}
  _onDragStart(event){const widget=event.target.closest?.('[data-widget-type]');if(widget){event.dataTransfer.effectAllowed='copy';event.dataTransfer.setData('application/x-upb-widget',widget.dataset.widgetType);this.shadowRoot.getElementById('canvas-frame').classList.add('dragging');return;}const nodeEl=event.target.closest?.('[data-upb-node]');if(nodeEl){event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('application/x-upb-node',nodeEl.dataset.upbNode);this.shadowRoot.getElementById('canvas-frame').classList.add('dragging');}}
  _onDragOver(event){if(event.target.closest?.('#page-preview,[data-drop-root]')){event.preventDefault();event.dataTransfer.dropEffect=event.dataTransfer.types.includes('application/x-upb-widget')?'copy':'move';}}
  _onDrop(event){event.preventDefault();if(!this._allowed('element.add')&&!this._allowed('element.move'))return;this.shadowRoot.getElementById('canvas-frame').classList.remove('dragging');const widgetType=event.dataTransfer.getData('application/x-upb-widget'),moveId=event.dataTransfer.getData('application/x-upb-node'),targetEl=event.target.closest?.('[data-upb-node]');let parentId=null,index=null;if(targetEl){const targetId=targetEl.dataset.upbNode,target=getNode(this._document,targetId);if(widgetDefinition(target?.type).acceptsChildren){parentId=targetId;}else{const parent=parentOf(this._document,targetId);parentId=parent?.id||null;const list=parent?parent.children:this._document.builder.root_ids;index=list.indexOf(targetId)+1;}}if(widgetType){if(!this._allowed('element.add'))return;const n=createNode(widgetType,createProps(widgetType));addNode(this._document,n,parentId,index);this._selected=n.id;this._mutated({checkpoint:true});return;}if(moveId&&this._allowed('element.move')&&getNode(this._document,moveId)&&moveNode(this._document,moveId,parentId,index)){this._selected=moveId;this._mutated({checkpoint:true});}}
  _moveSibling(id,delta){if(!this._allowed('element.move'))return;const parent=parentOf(this._document,id),list=parent?parent.children:this._document.builder.root_ids,from=list.indexOf(id),to=from+delta;if(from<0||to<0||to>=list.length)return;list.splice(to,0,list.splice(from,1)[0]);this._mutated({checkpoint:true});}
  _deleteNode(id){if(!this._allowed('element.delete')){this._notice('Seu perfil não pode excluir elementos.','error');return;}if(!getNode(this._document,id))return;removeNode(this._document,id);this._selected=parentOf(this._document,id)?.id||this._document.builder.root_ids[0]||null;this._mutated({checkpoint:true});}
  _replaceDocument(value,message=null){this._document=normalizeDocument(value);this._selected=this._document.builder.root_ids[0]||null;this._dirty=true;this._history.checkpoint(this._document);this._renderAll();this._scheduleAutosave();if(message)this._notice(message);this._emitChange();}
  _mutated({checkpoint=false,renderInspector=true,renderLeft=true,message=null}={}){this._dirty=true;if(checkpoint)this._history.checkpoint(this._document);this._renderToolbar();if(renderLeft)this._renderLeft();this._scheduleCanvasRender();if(renderInspector)this._renderInspector();this._scheduleAutosave();if(message)this._notice(message);this._emitChange();}
  _emitChange(){this.dispatchEvent(new CustomEvent('upb-change',{detail:{document:this.document},bubbles:true,composed:true}));}
  _undo(){if(!this._history.canUndo())return;this._document=normalizeDocument(this._history.undo());if(this._selected&&!getNode(this._document,this._selected))this._selected=this._document.builder.root_ids[0]||null;this._dirty=true;this._renderAll();this._scheduleAutosave();}
  _redo(){if(!this._history.canRedo())return;this._document=normalizeDocument(this._history.redo());this._dirty=true;this._renderAll();this._scheduleAutosave();}
  _copySelected(){if(!this._selected)return;this._clipboard=exportSubtree(this._document,this._selected);this._notice('Elemento copiado.');}
  _pasteSelected(){if(!this._clipboard)return;let parentId=null,index=null;if(this._selected){const selected=getNode(this._document,this._selected);if(widgetDefinition(selected?.type).acceptsChildren)parentId=selected.id;else{const parent=parentOf(this._document,this._selected);parentId=parent?.id||null;const list=parent?parent.children:this._document.builder.root_ids;index=list.indexOf(this._selected)+1;}}const inserted=importSubtree(this._document,this._clipboard,parentId,index);if(inserted){this._selected=inserted.id;this._mutated({checkpoint:true});}}
  _onKeyboard(event){if(!this.isConnected)return;const active=this.shadowRoot.activeElement,typing=active&&(['INPUT','TEXTAREA','SELECT'].includes(active.tagName)||active.isContentEditable),mod=event.ctrlKey||event.metaKey,key=event.key.toLowerCase();if(mod&&key==='s'){event.preventDefault();void this.save();}else if(mod&&key==='z'){event.preventDefault();event.shiftKey?this._redo():this._undo();}else if(mod&&key==='y'){event.preventDefault();this._redo();}else if(mod&&key==='c'&&!typing){event.preventDefault();this._copySelected();}else if(mod&&key==='v'&&!typing){event.preventDefault();this._pasteSelected();}else if(mod&&key==='d'&&!typing&&this._selected&&this._allowed('element.add')){event.preventDefault();const copy=duplicateNode(this._document,this._selected);if(copy){this._selected=copy.id;this._mutated({checkpoint:true});}}else if(!typing&&event.key==='Delete'&&this._selected){event.preventDefault();this._deleteNode(this._selected);}else if(event.key==='Escape'){this._mobileDrawer=null;this._renderToolbar();}}
  _onBeforeUnload(event){if(!this._dirty)return;event.preventDefault();event.returnValue='';}
  _scheduleAutosave(){if(!this._adapter?.autosave)return;if(this._autosaveTimer)clearTimeout(this._autosaveTimer);this._autosaveTimer=setTimeout(()=>{if(this._dirty&&!this._saving&&!this._publishing)void this.save({autosave:true}).catch(()=>{});},1200);}
  async _importFile(event){if(!this._allowed('page.import'))return;const file=event.target.files?.[0];event.target.value='';if(!file)return;try{const json=JSON.parse(await file.text());this._replaceDocument(json,'Documento importado e migrado para o formato atual.');}catch(error){this._notice(`Arquivo inválido: ${error?.message||error}`,'error');}}
  async _uploadImage(input){if(!this._allowed('asset.upload')){this._notice('Seu perfil não pode enviar ativos.','error');return;}const file=input.files?.[0];if(!file||!this._selected)return;try{this._status('Enviando imagem…');const url=await this._adapter.upload(file);const node=getNode(this._document,this._selected);if(node){node.props.image=url;this._mutated({checkpoint:true,message:'Imagem enviada.'});}}catch(error){this._notice(error?.message||'Falha no upload.','error');}finally{input.value='';this._status('');}}
  async _applyRemoteTemplate(key){if(!this._allowed('template.apply'))return;if(!this._adapter.applyTemplate)return;try{this._status('Aplicando modelo…');await this._adapter.applyTemplate(key);await this.load();this._notice('Modelo aplicado.');}catch(error){this._notice(error?.message||'Falha ao aplicar modelo.','error');}finally{this._status('');}}
  async _loadVersions(notify=false){if(!this._adapter.versions)return;try{this._remoteVersions=await this._adapter.versions();if(this._rightTab==='history')this._renderInspector();if(notify)this._notice('Histórico atualizado.');}catch(error){this._notice(error?.message||'Falha ao carregar versões.','error');}}
  async _restoreVersion(id){if(!this._allowed('history.restore'))return;if(!this._adapter.restoreVersion)return;try{await this._adapter.restoreVersion(id);await this.load();this._notice('Versão restaurada como rascunho.');}catch(error){this._notice(error?.message||'Falha ao restaurar versão.','error');}}
  _saveToLibrary(id){if(!this._allowed('library.manage'))return;const node=getNode(this._document,id);if(!node)return;const name=globalThis.prompt?.('Nome do componente reutilizável:',widgetDefinition(node.type).label)||'';if(!name.trim())return;this._library.saveFromDocument(this._document,id,{name:name.trim()});this._leftTab='library';this._renderAll();this._notice('Componente salvo na biblioteca.');}
  _insertLibrary(id){if(!this._allowed('element.add'))return;let parentId=null;if(this._selected&&widgetDefinition(getNode(this._document,this._selected)?.type).acceptsChildren)parentId=this._selected;const node=this._library.insert(this._document,id,parentId);if(node){this._selected=node.id;this._mutated({checkpoint:true});}}
  _addBreakpoint(){if(!this._allowed('design_system.edit'))return;const label=globalThis.prompt?.('Nome do breakpoint:','Notebook')||'';if(!label.trim())return;const max=Number(globalThis.prompt?.('Largura máxima em px:','1366')||1366);const id=label.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||`bp-${Date.now()}`;if(this._breakpoints().some(bp=>bp.id===id)){this._notice('Já existe um breakpoint com esse nome.','error');return;}this._document.design_system.breakpoints.push({id,label:label.trim(),max:Math.max(240,max),canvas:Math.max(240,Math.min(max,1180))});this._document.design_system.breakpoints=normalizeBreakpoints(this._document.design_system.breakpoints);for(const node of Object.values(this._document.builder.nodes)){node.responsive[id]={};node.responsive.hidden[id]=false;node.responsive_states[id]={hover:{},focus:{},active:{}};}this._mutated({checkpoint:true});}
  _deleteBreakpoint(id){if(!this._allowed('design_system.edit'))return;if(['desktop','tablet','mobile'].includes(id))return;this._document.design_system.breakpoints=this._document.design_system.breakpoints.filter(bp=>bp.id!==id);for(const node of Object.values(this._document.builder.nodes)){delete node.responsive[id];delete node.responsive.hidden[id];delete node.responsive_states[id];}if(this._device===id)this._device='desktop';this._mutated({checkpoint:true});}
  _previewWindow(){const html=exportStandaloneHtml(this.document,{context:this._context});const url=URL.createObjectURL(new Blob([html],{type:'text/html'}));window.open(url,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(url),60000);}
  _slugName(){return String(this._document.title||'landing-page').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'landing-page';}
  _status(text){const el=this.shadowRoot?.getElementById('save-status');if(el)el.innerHTML=text?`<span class="status-dot"></span>${esc(text)}`:'';}
  _notice(message,type='success'){const host=this.shadowRoot.getElementById('notice-host');host.innerHTML=`<div class="notice ${type==='error'?'error':''}">${esc(message)}</div>`;setTimeout(()=>{if(host.textContent===String(message))host.innerHTML='';},3500);}
}

if(globalThis.customElements && !customElements.get('argws-visual-builder'))customElements.define('argws-visual-builder',ArgwsVisualBuilder);
