export type Device = string;
export interface Breakpoint { id:string; label:string; max:number|null; canvas:number; }
export interface ResponsiveStyles { [device:string]:Record<string,unknown>|Record<string,boolean>; hidden:Record<string,boolean>; }
export interface NodeCondition { path:string; operator?:string; value?:unknown; logic?:'and'|'or'; }
export interface PageNode {
  id:string; type:string; props:Record<string,unknown>; style:Record<string,unknown>; states:Record<'hover'|'focus'|'active',Record<string,unknown>>;
  responsive:ResponsiveStyles; responsive_states:Record<string,Record<'hover'|'focus'|'active',Record<string,unknown>>>; bindings:Record<string,unknown>;
  conditions:NodeCondition[]; interactions:Array<{event:string;actions:unknown[]}>; motion:Record<string,unknown>; children:string[]; meta:Record<string,unknown>;
}
export interface PageDocument {
  schema:string; version:number; surface:string; title:string; settings:Record<string,unknown>; global_styles:Record<string,unknown>;
  design_system:{breakpoints:Breakpoint[];variables:Record<string,string>;classes:Record<string,unknown>}; seo:Record<string,unknown>;
  builder:{schema:string;root_ids:string[];nodes:Record<string,PageNode>}; project:Record<string,any>; blocks:unknown[];
}
export interface PageAdapter { load():Promise<PageDocument>; saveDraft(document:PageDocument):Promise<unknown>; autosave?(document:PageDocument):Promise<unknown>; publish(document:PageDocument):Promise<unknown>; listTemplates?():Promise<unknown[]>; versions?():Promise<unknown[]>; restoreVersion?(id:string):Promise<unknown>; upload?(file:File):Promise<string>; }
export const SCHEMA:string; export const DEVICES:string[]; export const DEFAULT_BREAKPOINTS:Breakpoint[];
export function uid(prefix?:string):string; export function deepClone<T>(value:T):T; export function responsive(breakpoints?:Breakpoint[]):ResponsiveStyles; export function normalizeBreakpoints(value:unknown):Breakpoint[];
export function createNode(type:string,props?:Record<string,unknown>,extra?:Partial<PageNode>):PageNode; export function createDocument(options?:Record<string,unknown>):PageDocument; export function normalizeDocument(input:unknown):PageDocument;
export function getBreakpoints(doc:PageDocument):Breakpoint[]; export function deviceForWidth(doc:PageDocument,width:number):string; export function getNode(doc:PageDocument,id:string):PageNode|null; export function addNode(doc:PageDocument,node:PageNode,parentId?:string|null,index?:number|null):PageNode; export function removeNode(doc:PageDocument,id:string):boolean; export function duplicateNode(doc:PageDocument,id:string):PageNode|null; export function moveNode(doc:PageDocument,id:string,parentId?:string|null,index?:number|null):boolean;
export function exportSubtree(doc:PageDocument,id:string):unknown; export function importSubtree(doc:PageDocument,bundle:unknown,parentId?:string|null,index?:number|null):PageNode|null;
export class HistoryStack { constructor(limit?:number); past:unknown[];future:unknown[]; reset(value:unknown):void; checkpoint(value:unknown):void; canUndo():boolean; canRedo():boolean; undo():unknown; redo():unknown; }
export const WIDGETS:Record<string,unknown>; export function registerWidget(type:string,definition:Record<string,unknown>):unknown; export function unregisterWidget(type:string):void; export function widgetDefinition(type:string):any; export function widgetGroups():Record<string,unknown[]>; export function createProps(type:string):Record<string,unknown>;
export function getPath(source:unknown,path:string,fallback?:unknown):unknown; export function interpolate(value:unknown,context?:Record<string,unknown>):unknown; export function resolveBindings(props:Record<string,unknown>,bindings:Record<string,unknown>,context?:Record<string,unknown>):Record<string,unknown>; export function evaluateConditions(conditions:NodeCondition[],context?:Record<string,unknown>):boolean;
export function registerRenderer(type:string,renderer:(context:any)=>string):void; export function unregisterRenderer(type:string):void; export function renderDocument(input:unknown,options?:{device?:string;context?:Record<string,unknown>;responsive?:boolean;locale?:string}):{html:string;css:string;document:PageDocument}; export function renderDocumentAsync(input:unknown,options?:Record<string,unknown>):Promise<{html:string;css:string;document:PageDocument;data_errors:unknown[];data_requirements:unknown[]}>; export function exportStandaloneHtml(input:unknown,options?:Record<string,unknown>):string; export function exportStandaloneHtmlAsync(input:unknown,options?:Record<string,unknown>):Promise<string>; export function toSchedulerProContent(input:unknown):Record<string,unknown>;
export function registerAction(name:string,handler:(context:any)=>unknown):unknown;export function unregisterAction(name:string):void;export function executeActions(actions:unknown[],payload?:Record<string,unknown>,runtime?:Record<string,unknown>):Promise<unknown[]>;
export class LocalComponentLibrary { constructor(options?:Record<string,unknown>);list():unknown[];saveFromDocument(document:PageDocument,nodeId:string,options?:Record<string,unknown>):unknown;remove(id:string):void;insert(document:PageDocument,id:string,parentId?:string|null,index?:number|null):PageNode|null;export():string;import(payload:unknown):unknown[]; }
export function auditDocument(input:unknown):{score:number;errors:number;warnings:number;issues:unknown[]};
export function createSiteKit(options?:Record<string,unknown>):unknown; export function resolveSiteParts(siteKit:unknown,type:string,context?:Record<string,unknown>):unknown[];
export function hydratePage(root:Element,options?:Record<string,unknown>):()=>void;
export class MemoryAdapter implements PageAdapter { constructor(initial?:unknown); load():Promise<PageDocument>; saveDraft(document:PageDocument):Promise<unknown>; autosave(document:PageDocument):Promise<unknown>; publish(document:PageDocument):Promise<unknown>;versions():Promise<unknown[]>;restoreVersion(id:string):Promise<unknown>; }
export class RestAdapter implements PageAdapter { constructor(options?:Record<string,unknown>); load():Promise<PageDocument>; saveDraft(document:PageDocument):Promise<unknown>; autosave(document:PageDocument):Promise<unknown>; publish(document:PageDocument):Promise<unknown>; listTemplates():Promise<unknown[]>;versions():Promise<unknown[]>;restoreVersion(id:string):Promise<unknown>;upload(file:File):Promise<string>; }
export class SchedulerProAdapter implements PageAdapter { constructor(options?:{baseUrl?:string;slug?:string;token?:()=>string}); load():Promise<PageDocument>; saveDraft(document:PageDocument):Promise<unknown>; autosave(document:PageDocument):Promise<unknown>; publish(document:PageDocument):Promise<unknown>; listTemplates():Promise<unknown[]>; applyTemplate(key:string):Promise<unknown>; versions():Promise<unknown[]>; restoreVersion(id:string):Promise<unknown>; services():Promise<unknown[]>; professionals():Promise<unknown[]>; upload(file:File):Promise<string>; }
export class ArgwsVisualBuilder extends HTMLElement { adapter:PageAdapter; document:PageDocument; context:Record<string,unknown>; load():Promise<void>; save(options?:{autosave?:boolean}):Promise<unknown>; publish():Promise<unknown>; }
export class ArgwsPageRenderer extends HTMLElement { document:PageDocument; context:Record<string,unknown>;runtime:Record<string,unknown>;deviceOverride:string|null; render():Promise<void>; }
export const BUILTIN_TEMPLATES:Array<{key:string;name:string;description:string;create:()=>PageDocument}>;

export function createPageDocument(options?:Record<string,unknown>):PageDocument;
export function compileSchedulerProV2(input:unknown):Record<string,unknown>;
export function renderPage(input:unknown,options?:{device?:string;context?:Record<string,unknown>;responsive?:boolean}):string; export function renderPageAsync(input:unknown,options?:Record<string,unknown>):Promise<string>;



export type DynamicFilter=(value:unknown,...args:unknown[])=>unknown;
export function registerDynamicFilter(name:string,handler:DynamicFilter):DynamicFilter; export function unregisterDynamicFilter(name:string):void; export function dynamicFilter(name:string):DynamicFilter|null;
export function registerDynamicTag(name:string,resolver:(context:Record<string,unknown>,args?:unknown[])=>unknown):unknown; export function unregisterDynamicTag(name:string):void; export function resolveRegisteredTag(name:string,context?:Record<string,unknown>,args?:unknown[]):unknown;
export function resolveDynamicExpression(expression:string,context?:Record<string,unknown>):unknown;
export class QueryCache { constructor();key(source:string,query?:Record<string,unknown>):string;get(source:string,query?:Record<string,unknown>):unknown;set(source:string,query:Record<string,unknown>,value:unknown,ttl?:number):unknown;clear():void; }
export function registerDataSource(name:string,handler:(query:Record<string,unknown>,runtime?:Record<string,unknown>)=>unknown):unknown; export function unregisterDataSource(name:string):void; export function listDataSources():string[]; export function executeDataQuery(source:string,query?:Record<string,unknown>,runtime?:Record<string,unknown>):Promise<unknown>; export function resolveDataRequirements(input:unknown,runtime?:Record<string,unknown>):Promise<{document:PageDocument;context:Record<string,unknown>}>;
export interface FormField {label:string;name:string;type:string;required:boolean;placeholder:string;value:unknown;options:unknown[];accept:string;step:number;min:unknown;max:unknown;}
export function normalizeFormField(field?:Partial<FormField>,index?:number):FormField; export function normalizeFormSchema(value?:Record<string,unknown>):{id:string;fields:FormField[];steps:number;actions:unknown[];success_message:string;error_message:string}; export function validateFormValues(schema:unknown,values?:Record<string,unknown>):{valid:boolean;errors:Record<string,string>}; export function parseFormFieldsText(value:unknown):FormField[];
export const ALL_CAPABILITIES:string[]; export function createEditorPolicy(options?:Record<string,unknown>):unknown; export function can(policy:unknown,capability:string):boolean; export function assertCan(policy:unknown,capability:string):true; export function policyForRole(role:string,overrides?:Record<string,unknown>):unknown;
export function localeConfig(input:unknown,locale?:string):unknown; export function localizeDocument(input:unknown,locale?:string):PageDocument; export function setNodeTranslation(input:unknown,locale:string,nodeId:string,props?:Record<string,unknown>):PageDocument;
export function createOperation(type:string,payload?:Record<string,unknown>,meta?:Record<string,unknown>):unknown; export function applyOperation(input:unknown,operation:unknown):PageDocument; export function applyOperations(input:unknown,operations?:unknown[]):PageDocument;
export class AssetLibrary { constructor(input?:Record<string,unknown>);list(type?:string):unknown[];add(type:string,asset:Record<string,unknown>):unknown;remove(type:string,id:string):boolean;toJSON():Record<string,unknown>; } export function fontFaceCss(input:unknown):string;
export const PROJECT_PACKAGE_SCHEMA:string; export function createProjectPackage(options?:Record<string,unknown>):unknown; export function validateProjectPackage(value:unknown):{valid:boolean;errors:string[]}; export function normalizeProjectPackage(value:unknown):unknown; export function exportProjectPackage(value:unknown):string; export function importProjectPackage(value:unknown):unknown;
export function normalizeCodeSnippet(value:unknown):unknown; export function renderCustomCode(snippets:unknown[],options?:Record<string,unknown>):{head:string;bodyStart:string;bodyEnd:string};
export function createEmbedSnippet(target:'html'|'blade'|'php'|'jinja2'|'twig'|'vue'|'react'|'svelte',options?:Record<string,unknown>):string;

export function registerHostService(name:string,handler:(context:any)=>unknown,options?:Record<string,unknown>):unknown; export function unregisterHostService(name:string):void; export function hostService(name:string):unknown; export function listHostServices():Array<{name:string;meta:Record<string,unknown>}>; export function invokeHostService(name:string,payload?:Record<string,unknown>,runtime?:Record<string,unknown>):Promise<unknown>;
export interface BuilderPluginManifest { id:string;name?:string;version?:string;description?:string;capabilities?:string[];widgets?:Record<string,unknown>;renderers?:Record<string,(context:any)=>string>;actions?:Record<string,(context:any)=>unknown>;dataSources?:Record<string,unknown>;dynamicTags?:Record<string,(context:any)=>unknown>;dynamicFilters?:Record<string,(value:unknown,...args:unknown[])=>unknown>;services?:Record<string,unknown>; }
export function registerBuilderPlugin(manifest:BuilderPluginManifest):unknown; export function unregisterBuilderPlugin(id:string):boolean; export function listBuilderPlugins():unknown[]; export function builderPlugin(id:string):unknown;

export interface SubmissionRecord {id:string;created_at:string;form_id:string;page_id?:string|null;values:Record<string,unknown>;meta:Record<string,unknown>;} export class MemorySubmissionStore {constructor(initial?:SubmissionRecord[]);create(input?:Partial<SubmissionRecord>):Promise<SubmissionRecord>;list(options?:{form_id?:string|null;limit?:number;offset?:number}):Promise<SubmissionRecord[]>;get(id:string):Promise<SubmissionRecord|null>;remove(id:string):Promise<boolean>;} export class RestSubmissionStore {constructor(options?:Record<string,unknown>);create(input:Partial<SubmissionRecord>):Promise<SubmissionRecord>;list(options?:Record<string,unknown>):Promise<SubmissionRecord[]>;get(id:string):Promise<SubmissionRecord|null>;remove(id:string):Promise<unknown>;} export function submissionsToCsv(rows?:SubmissionRecord[]):string;
