const field = (key, label, control = 'text', defaultValue = '', extra = {}) => ({ key, label, control, default: defaultValue, ...extra });
const text = (key, label, defaultValue = '', extra = {}) => field(key, label, 'text', defaultValue, extra);
const textarea = (key, label, defaultValue = '', extra = {}) => field(key, label, 'textarea', defaultValue, extra);
const toggle = (key, label, defaultValue = false, extra = {}) => field(key, label, 'toggle', defaultValue, extra);
const select = (key, label, options, defaultValue, extra = {}) => field(key, label, 'select', defaultValue, { options, ...extra });
const number = (key, label, defaultValue = 0, min = 0, max = 9999, extra = {}) => field(key, label, 'number', defaultValue, { min, max, ...extra });

export const WIDGETS = {
  container: { label: 'Container Flex', group: 'Layout', icon: '▣', acceptsChildren: true, defaults: { direction: 'column', gap: 20, align: 'stretch', justify: 'flex-start', wrap: 'nowrap', max_width: 1180 }, fields: [select('direction','Direção',[['row','Horizontal'],['column','Vertical'],['row-reverse','Horizontal reverso'],['column-reverse','Vertical reverso']],'column'), select('wrap','Quebra',[['nowrap','Sem quebra'],['wrap','Quebrar'],['wrap-reverse','Quebra reversa']],'nowrap'), number('gap','Espaço',20,0,240), number('max_width','Largura máxima',1180,240,3000)] },
  grid: { label: 'Container Grid', group: 'Layout', icon: '▦', acceptsChildren: true, defaults: { columns: 3, gap: 20, min_column: 220 }, fields: [number('columns','Colunas',3,1,12), number('gap','Espaço',20,0,240), number('min_column','Coluna mínima',220,80,1200)] },
  hero: { label: 'Hero', group: 'Marketing', icon: '★', defaults: { eyebrow:'Seu negócio',title:'Transforme visitantes em clientes',text:'Construa uma apresentação clara e conduza o visitante para a ação.',cta:'Começar agora',cta_url:'#agendamento',image:'' }, fields:[text('eyebrow','Sobretítulo'),text('title','Título','',{inline:true}),textarea('text','Texto'),text('cta','Texto do botão'),text('cta_url','Link do botão'),text('image','Imagem (URL)')] },
  heading: { label: 'Título', group: 'Básico', icon: 'H', defaults:{text:'Novo título',level:'h2'}, fields:[text('text','Texto','',{inline:true}),select('level','Nível',[['h1','H1'],['h2','H2'],['h3','H3'],['h4','H4'],['h5','H5'],['h6','H6']],'h2')] },
  title: { label: 'Título compatível', group: 'Scheduler Pro', icon: 'T', defaults:{text:'Novo título'}, fields:[text('text','Texto','',{inline:true})] },
  subtitle: { label: 'Subtítulo', group: 'Scheduler Pro', icon: 't', defaults:{text:'Novo subtítulo'}, fields:[text('text','Texto','',{inline:true})] },
  text: { label:'Texto', group:'Básico', icon:'¶', defaults:{title:'',text:'Digite seu texto aqui.'}, fields:[text('title','Título','',{inline:true}),textarea('text','Texto','',{inline:true})] },
  rich_text: { label:'Texto rico', group:'Básico', icon:'Aa', defaults:{html:'<p>Digite seu conteúdo.</p>'}, fields:[textarea('html','Conteúdo HTML seguro')] },
  button: { label:'Botão', group:'Básico', icon:'▰', defaults:{label:'Saiba mais',url:'#',action:'link',target:'',new_tab:false}, fields:[text('label','Rótulo','',{inline:true}),select('action','Ação',[['link','Abrir link'],['scroll','Ir para âncora'],['popup','Abrir popup/off-canvas']],'link'),text('url','Link / Âncora'),text('target','ID do popup'),toggle('new_tab','Abrir em nova aba',false)] },
  image: { label:'Imagem', group:'Básico', icon:'▧', defaults:{image:'',alt:'Imagem',caption:'',lightbox:false}, fields:[text('image','URL da imagem'),text('alt','Texto alternativo'),text('caption','Legenda'),toggle('lightbox','Abrir em lightbox',false)] },
  icon: { label:'Ícone', group:'Básico', icon:'◆', defaults:{icon:'★',label:'',url:''}, fields:[text('icon','Ícone / símbolo'),text('label','Rótulo acessível'),text('url','Link')] },
  icon_box: { label:'Caixa de ícone', group:'Marketing', icon:'◈', defaults:{icon:'✓',title:'Benefício',text:'Explique o benefício de forma objetiva.'}, fields:[text('icon','Ícone'),text('title','Título','',{inline:true}),textarea('text','Texto')] },
  video: { label:'Vídeo', group:'Básico', icon:'▶', defaults:{title:'Vídeo',url:'',poster:'',autoplay:false}, fields:[text('title','Título'),text('url','URL'),text('poster','Poster'),toggle('autoplay','Autoplay',false)] },
  divider: { label:'Divisor', group:'Básico', icon:'—', defaults:{}, fields:[] },
  spacer: { label:'Espaçador', group:'Básico', icon:'↕', defaults:{height:32}, fields:[number('height','Altura',32,0,1000)] },
  gallery: { label:'Galeria', group:'Marketing', icon:'▦', defaults:{title:'Galeria',layout:'grid',images:[]}, fields:[text('title','Título'),select('layout','Layout',[['grid','Grade'],['editorial','Editorial'],['masonry','Masonry visual']],'grid'),textarea('images_text','URLs (uma por linha)')] },
  carousel: { label:'Carrossel', group:'Marketing', icon:'◫', defaults:{title:'Destaques',images:[],autoplay:false,interval:5000}, fields:[text('title','Título'),textarea('images_text','URLs (uma por linha)'),toggle('autoplay','Autoplay',false),number('interval','Intervalo (ms)',5000,1000,30000)] },
  card: { label:'Card', group:'Marketing', icon:'▤', defaults:{title:'Título do card',text:'Conteúdo do card',url:''}, fields:[text('title','Título','',{inline:true}),textarea('text','Texto'),text('url','Link')] },
  list: { label:'Lista', group:'Básico', icon:'☷', defaults:{title:'Lista',items_text:'Primeiro item\nSegundo item'}, fields:[text('title','Título'),textarea('items_text','Itens, um por linha')] },
  counter: { label:'Contador', group:'Marketing', icon:'123', defaults:{start:0,end:100,suffix:'+',duration:1400,title:'Resultados'}, fields:[number('start','Início',0,-999999,999999),number('end','Fim',100,-999999,999999),text('suffix','Sufixo'),number('duration','Duração (ms)',1400,100,10000),text('title','Legenda')] },
  progress: { label:'Progresso', group:'Marketing', icon:'▰', defaults:{title:'Progresso',value:75,label:'75%'}, fields:[text('title','Título'),number('value','Valor',75,0,100),text('label','Rótulo')] },
  rating: { label:'Avaliação', group:'Marketing', icon:'★★★★★', defaults:{value:5,max:5,label:'5 de 5'}, fields:[number('value','Nota',5,0,10),number('max','Máximo',5,1,10),text('label','Descrição')] },
  price_table: { label:'Tabela de preço', group:'Marketing', icon:'$', defaults:{name:'Plano Pro',price:'R$ 199',period:'/mês',features_text:'Recurso 1\nRecurso 2\nRecurso 3',button:'Escolher',url:'#'}, fields:[text('name','Plano'),text('price','Preço'),text('period','Período'),textarea('features_text','Recursos'),text('button','Botão'),text('url','Link')] },
  testimonials: { label:'Depoimentos', group:'Marketing', icon:'❝', defaults:{title:'Depoimentos',items:[]}, fields:[text('title','Título'),textarea('items_text','Itens: Nome | Texto, um por linha')] },
  faq: { label:'FAQ', group:'Marketing', icon:'?', defaults:{title:'Perguntas frequentes',items:[]}, fields:[text('title','Título'),textarea('items_text','Itens: Pergunta | Resposta, um por linha')] },
  accordion: { label:'Acordeão', group:'Interativo', icon:'≡', defaults:{title:'Perguntas',items:[]}, fields:[text('title','Título'),textarea('items_text','Itens: Título | Conteúdo, um por linha')] },
  tabs: { label:'Abas', group:'Interativo', icon:'▥', defaults:{items:[]}, fields:[textarea('items_text','Abas: Título | Conteúdo, uma por linha')] },
  alert: { label:'Aviso', group:'Básico', icon:'!', defaults:{title:'Atenção',text:'Mensagem importante.',kind:'info'}, fields:[text('title','Título'),textarea('text','Mensagem'),select('kind','Tipo',[['info','Informação'],['success','Sucesso'],['warning','Aviso'],['danger','Erro']],'info')] },
  nav_menu: { label:'Menu', group:'Site', icon:'☰', defaults:{brand:'',items_text:'Início | #inicio\nContato | #contato',mobile:true}, fields:[text('brand','Marca'),textarea('items_text','Itens: Rótulo | URL'),toggle('mobile','Menu responsivo',true)] },
  breadcrumbs: { label:'Breadcrumbs', group:'Site', icon:'›', defaults:{items_text:'Início | /\nPágina | #'}, fields:[textarea('items_text','Itens: Rótulo | URL')] },
  services: { label:'Serviços', group:'Scheduler Pro', icon:'✦', defaults:{title:'Serviços',subtitle:'Escolha o atendimento ideal',show_prices:true}, fields:[text('title','Título'),text('subtitle','Subtítulo'),toggle('show_prices','Mostrar preços',true)] },
  professionals: { label:'Profissionais', group:'Scheduler Pro', icon:'♙', defaults:{title:'Profissionais',layout:'cards'}, fields:[text('title','Título')] },
  booking: { label:'Agenda / Agendamento', group:'Scheduler Pro', icon:'▣', defaults:{title:'Escolha seu horário',subtitle:'Selecione serviço, profissional, data e horário.'}, fields:[text('title','Título'),text('subtitle','Subtítulo')] },
  business_hours: { label:'Horários', group:'Scheduler Pro', icon:'◷', defaults:{title:'Horários de atendimento'}, fields:[text('title','Título')] },
  address: { label:'Endereço', group:'Scheduler Pro', icon:'⌖', defaults:{title:'Onde estamos',address:'',show_map:true}, fields:[text('title','Título'),textarea('address','Endereço'),toggle('show_map','Mostrar mapa',true)] },
  contact: { label:'Contato', group:'Scheduler Pro', icon:'☎', defaults:{title:'Contato',phone:'',email:''}, fields:[text('title','Título'),text('phone','Telefone'),text('email','E-mail')] },
  social: { label:'Redes sociais', group:'Marketing', icon:'◎', defaults:{title:'Redes sociais',instagram:'',facebook:'',tiktok:'',youtube:'',linkedin:''}, fields:[text('title','Título'),text('instagram','Instagram'),text('facebook','Facebook'),text('tiktok','TikTok'),text('youtube','YouTube'),text('linkedin','LinkedIn')] },
  whatsapp_button: { label:'WhatsApp', group:'Scheduler Pro', icon:'◉', defaults:{label:'Falar pelo WhatsApp',phone:'',message:''}, fields:[text('label','Rótulo'),text('phone','Telefone'),text('message','Mensagem inicial')] },
  cta: { label:'Chamada para ação', group:'Marketing', icon:'→', defaults:{title:'Pronto para começar?',text:'Escolha a melhor opção para você.',button:'Continuar',url:'#'}, fields:[text('title','Título'),textarea('text','Texto'),text('button','Botão'),text('url','Link')] },
  form: { label:'Formulário', group:'Interativo', icon:'▧', defaults:{title:'Entre em contato',submit_label:'Enviar',previous_label:'Voltar',next_label:'Continuar',fields_text:'Nome | name | text | required | | 1\nE-mail | email | email | required | | 1\nMensagem | message | textarea | required | | 1',fields_json:'',actions_text:'event',actions_json:'',multi_step:false,success_message:'Recebemos sua mensagem.'}, fields:[text('title','Título'),textarea('fields_text','Campos: Rótulo | nome | tipo | required | opções | etapa'),textarea('fields_json','Schema de campos JSON (opcional)'),textarea('actions_text','Ações simples: event, webhook'),textarea('actions_json','Ações JSON (opcional)'),toggle('multi_step','Formulário multi-etapa',false),text('previous_label','Botão voltar'),text('next_label','Botão continuar'),text('submit_label','Botão enviar'),text('success_message','Mensagem de sucesso')] },
  loop: { label:'Loop / Repetidor', group:'Dinâmico', icon:'∞', acceptsChildren:true, defaults:{source:'items',limit:12,empty:'Nenhum item encontrado.'}, fields:[text('source','Caminho da coleção'),number('limit','Limite',12,1,200),text('empty','Mensagem vazia')] },
  dynamic_text: { label:'Texto dinâmico', group:'Dinâmico', icon:'ƒx', defaults:{path:'tenant.name',fallback:'Conteúdo dinâmico',prefix:'',suffix:''}, fields:[text('path','Caminho dos dados'),text('fallback','Fallback'),text('prefix','Prefixo'),text('suffix','Sufixo')] },
  popup: { label:'Popup', group:'Interativo', icon:'▣', acceptsChildren:true, defaults:{name:'popup',trigger:'manual',delay:3000,scroll_percent:50,width:560,close_label:'Fechar'}, fields:[text('name','Identificador'),select('trigger','Gatilho',[['manual','Manual / botão'],['delay','Após tempo'],['scroll','Ao rolar'],['exit','Intenção de saída']],'manual'),number('delay','Atraso (ms)',3000,0,600000),number('scroll_percent','Rolagem (%)',50,1,100),number('width','Largura',560,280,1400),text('close_label','Rótulo fechar')] },
  offcanvas: { label:'Off Canvas', group:'Interativo', icon:'▤', acceptsChildren:true, defaults:{name:'offcanvas',side:'right',width:420,close_label:'Fechar'}, fields:[text('name','Identificador'),select('side','Lado',[['left','Esquerda'],['right','Direita']],'right'),number('width','Largura',420,260,1000),text('close_label','Rótulo fechar')] },
  countdown: { label:'Contagem regressiva', group:'Marketing', icon:'◷', defaults:{target:'',expired_text:'Encerrado'}, fields:[text('target','Data/hora ISO'),text('expired_text','Texto ao terminar')] },
  embed: { label:'Embed seguro', group:'Avançado', icon:'<>', defaults:{url:'',title:'Conteúdo incorporado'}, fields:[text('url','URL HTTPS'),text('title','Título')] },
  html: { label:'HTML seguro', group:'Avançado', icon:'</>', defaults:{html:'<p>HTML personalizado</p>'}, fields:[textarea('html','HTML')] },
  query_loop: { label:'Query Loop', group:'Dinâmico', icon:'⌘', acceptsChildren:true, defaults:{source:'content.items',query_json:'{}',limit:12,empty:'Nenhum item encontrado.'}, fields:[text('source','Data Source'),textarea('query_json','Query JSON','{}'),number('limit','Limite',12,1,500),text('empty','Mensagem vazia')] },
  nested_tabs: { label:'Abas aninhadas', group:'Interativo', icon:'▥', acceptsChildren:true, defaults:{orientation:'horizontal',accordion_breakpoint:'mobile'}, fields:[select('orientation','Orientação',[['horizontal','Horizontal'],['vertical','Vertical']],'horizontal'),text('accordion_breakpoint','Virar acordeão no breakpoint')] },
  tab_item: { label:'Item de aba', group:'Estrutural', icon:'▱', acceptsChildren:true, defaults:{title:'Nova aba',icon:''}, fields:[text('title','Título'),text('icon','Ícone')] },
  nested_accordion: { label:'Acordeão aninhado', group:'Interativo', icon:'≡', acceptsChildren:true, defaults:{multiple:false}, fields:[toggle('multiple','Permitir múltiplos abertos',false)] },
  accordion_item: { label:'Item de acordeão', group:'Estrutural', icon:'▰', acceptsChildren:true, defaults:{title:'Novo item',open:false}, fields:[text('title','Título'),toggle('open','Aberto inicialmente',false)] },
  mega_menu: { label:'Mega Menu', group:'Site', icon:'☷', acceptsChildren:true, defaults:{brand:'Marca',trigger:'click',mobile_breakpoint:'tablet'}, fields:[text('brand','Marca'),select('trigger','Abrir submenu',[['click','Clique'],['hover','Hover']],'click'),text('mobile_breakpoint','Breakpoint mobile')] },
  menu_item: { label:'Item de menu', group:'Estrutural', icon:'›', acceptsChildren:true, defaults:{label:'Menu',url:'#',panel:false}, fields:[text('label','Rótulo'),text('url','URL'),toggle('panel','Usar filhos como mega painel',false)] },
  floating_bar: { label:'Barra flutuante', group:'Marketing', icon:'═', acceptsChildren:true, defaults:{position:'bottom',dismissible:true,sticky:true}, fields:[select('position','Posição',[['top','Topo'],['bottom','Rodapé']],'bottom'),toggle('dismissible','Pode fechar',true),toggle('sticky','Fixa',true)] },
  table_of_contents: { label:'Sumário', group:'Site', icon:'☷', defaults:{title:'Nesta página',levels:'h2,h3',ordered:false}, fields:[text('title','Título'),text('levels','Níveis HTML'),toggle('ordered','Lista numerada',false)] },
  search: { label:'Busca', group:'Site', icon:'⌕', defaults:{placeholder:'Buscar…',action:'/buscar',method:'get',param:'q'}, fields:[text('placeholder','Placeholder'),text('action','URL da busca'),select('method','Método',[['get','GET'],['post','POST']],'get'),text('param','Parâmetro')] },
  share_buttons: { label:'Compartilhar', group:'Marketing', icon:'↗', defaults:{title:'Compartilhe',networks:'whatsapp,facebook,linkedin,x,email'}, fields:[text('title','Título'),text('networks','Redes (separadas por vírgula)')] },
  map: { label:'Mapa / localização', group:'Básico', icon:'⌖', defaults:{title:'Localização',embed_url:'',address:''}, fields:[text('title','Título'),text('embed_url','URL de incorporação'),textarea('address','Endereço')] },
  lottie: { label:'Animação Lottie', group:'Marketing', icon:'✦', defaults:{url:'',loop:true,autoplay:true,label:'Animação'}, fields:[text('url','JSON Lottie URL'),toggle('loop','Loop',true),toggle('autoplay','Autoplay',true),text('label','Rótulo acessível')] },
  hotspot: { label:'Hotspots', group:'Marketing', icon:'⊙', defaults:{image:'',alt:'Imagem interativa',items_json:'[{"x":50,"y":50,"label":"Ponto 1","text":"Detalhe"}]'}, fields:[text('image','Imagem'),text('alt','Texto alternativo'),textarea('items_json','Hotspots JSON')] },
  flip_box: { label:'Flip Box', group:'Marketing', icon:'↻', defaults:{front_title:'Frente',front_text:'Conteúdo inicial',back_title:'Verso',back_text:'Conteúdo ao interagir',button:'Saiba mais',url:'#'}, fields:[text('front_title','Título frente'),textarea('front_text','Texto frente'),text('back_title','Título verso'),textarea('back_text','Texto verso'),text('button','Botão'),text('url','URL')] },
  slides: { label:'Slides', group:'Marketing', icon:'▧', defaults:{slides_json:'[{"title":"Slide 1","text":"Conteúdo","image":"","button":"Saiba mais","url":"#"}]',autoplay:true,interval:5000}, fields:[textarea('slides_json','Slides JSON'),toggle('autoplay','Autoplay',true),number('interval','Intervalo',5000,1000,30000)] },
  host_component: { label:'Componente do projeto', group:'Dinâmico', icon:'◇', defaults:{name:'component',fallback:'Componente fornecido pelo projeto hospedeiro.'}, fields:[text('name','Nome do componente'),textarea('fallback','Fallback')] },
  login_form: { label:'Login', group:'Interativo', icon:'⇥', defaults:{title:'Entrar',identity_label:'E-mail',password_label:'Senha',submit_label:'Entrar',action:'auth.login'}, fields:[text('title','Título'),text('identity_label','Campo usuário'),text('password_label','Campo senha'),text('submit_label','Botão'),text('action','Ação do host')] },
  commerce_product_grid: { label:'Grade de produtos', group:'Commerce', icon:'▦', defaults:{component:'commerce.product_grid',title:'Produtos',query_json:'{}',columns:4,fallback:'Catálogo fornecido pelo provider de commerce.'}, fields:[text('title','Título'),text('component','Componente do host'),textarea('query_json','Query JSON'),number('columns','Colunas',4,1,8),textarea('fallback','Fallback')] },
  commerce_product: { label:'Produto', group:'Commerce', icon:'◫', defaults:{component:'commerce.product',product_id:'',fallback:'Produto fornecido pelo provider de commerce.'}, fields:[text('component','Componente do host'),text('product_id','ID / referência do produto'),textarea('fallback','Fallback')] },
  commerce_cart: { label:'Carrinho', group:'Commerce', icon:'▤', defaults:{component:'commerce.cart',fallback:'Carrinho fornecido pelo provider de commerce.'}, fields:[text('component','Componente do host'),textarea('fallback','Fallback')] },
  commerce_checkout: { label:'Checkout', group:'Commerce', icon:'✓', defaults:{component:'commerce.checkout',fallback:'Checkout fornecido pelo provider de commerce.'}, fields:[text('component','Componente do host'),textarea('fallback','Fallback')] },
  commerce_account: { label:'Conta do cliente', group:'Commerce', icon:'◎', defaults:{component:'commerce.account',fallback:'Área do cliente fornecida pelo provider de commerce.'}, fields:[text('component','Componente do host'),textarea('fallback','Fallback')] },
  cookie_consent: { label:'Consentimento de cookies', group:'Site', icon:'◌', defaults:{text:'Utilizamos cookies para melhorar sua experiência.',accept:'Aceitar',reject:'Recusar',policy_url:'/privacidade'}, fields:[textarea('text','Texto'),text('accept','Aceitar'),text('reject','Recusar'),text('policy_url','Política')] },
  code_block: { label:'Código', group:'Avançado', icon:'{}', defaults:{code:'const hello = "world";',language:'javascript',show_lines:true}, fields:[textarea('code','Código'),text('language','Linguagem'),toggle('show_lines','Mostrar linhas',true)] },
  anchor: { label:'Âncora', group:'Básico', icon:'#', defaults:{name:'secao'}, fields:[text('name','ID da âncora')] },
  footer: { label:'Rodapé', group:'Site', icon:'▁', defaults:{text:'Todos os direitos reservados.'}, fields:[text('text','Texto')] },
};

export function widgetDefinition(type) { return WIDGETS[type] || { label:type, group:'Outros', icon:'◇', defaults:{title:'Novo bloco'}, fields:[text('title','Título')] }; }
export function widgetGroups() {
  const groups = {};
  for (const [type, def] of Object.entries(WIDGETS)) (groups[def.group] ||= []).push({ type, ...def });
  return groups;
}
export function createProps(type) { return JSON.parse(JSON.stringify(widgetDefinition(type).defaults || {})); }

export function registerWidget(type, definition) {
  if (!/^[a-z][a-z0-9_-]{1,63}$/.test(String(type))) throw new Error('Tipo de widget inválido.');
  if (!definition || typeof definition !== 'object' || !definition.label) throw new Error('Definição de widget inválida.');
  WIDGETS[type] = { group:'Extensões', icon:'◇', defaults:{}, fields:[], ...definition };
  return WIDGETS[type];
}

export function unregisterWidget(type) { delete WIDGETS[type]; }
